## WHAT IS DATA WRANGLING OR DATA MUNGING?

DATA WRANGLING is the art of dealing with and or converting missing or ill-formatted data into a format that more easily lends itself to analysis.

BUT, HOW TO ORGANIZE MESSI DATA?

FIRST, TRY TO UNDERSTAND THE STRUCTURE OF THE DATA ITSELF.

BUT, before we can make this analysis, we need first to get the data we want to analyze. Three of the most common sources to get the data are from FILES, DATABASES AND WEBSITES THROUGH WEB APIs.

##### ACQUIRING DATA

Acquiring data is not a fancy thing. It is just a matter of finding the right file in the internet and downloading it. The most of the data are stored in text files, particularly on government websites. Normally, files can come in one of these formats.

#### COMMON DATA FORMATS

###### CSV ------------------------- XML --------------------------- JSON

#### Note: it is recommended to take the course Data Wrangling with mongoDB.

CSV: it has a series of rows. Each row corresponding to an entry. The first row of every file tells us what each entry means. The values of the first row can be called as the identifiers.

XML: the benefit in comparison to CSV is that it supports nested structures. 
A document element can have a series of tables, which can have a number of children (every row/column).

<Document Element>
    <Table>
        <Column1> Value <Column1/>
        <Column2> Value <Column2/>
        <Column3/> #Value missing               
    <Table/>
    
JSON: the benefit in comparison to CSV is that it supports nested structures. Json documents have a number of json objects. It looks like a python dictionary. We have keys, which corresponds to what we see in the header row in a CSV file, followed by values.

{
    'Key1': value1,
    'Key2': value2,
    'Key3': value3,
}

##### Note: data format is not a matter of the file extension, being .csv or .json. A file format really has to do with how the data is organized inside the file. We could have data that is formatted in json or csv, but that comes in a file whose extension is .txt

#### SOURCES OF DATA

FILE ---------------------- DATABASES ---------------------- WEB APIs

Once we ACQUIRE the data, it is always good to make a SANITY CHECKING because our data could have bad or missing values. 

#### What is SANITY CHECKING?

With sanity checking we answer questions like, does our data make sense? Is there a problem? Does the data look like I expected to?

How to do it? you can draw plots to visualize the data or run some analysis somehow. But pandas has a method for that, the method describe.

#### Note: it is recommended to take udacitys course: exploratoy data and analysis course.

In [1]:
import pandas as pd
from pandasql import sqldf
import numpy as np
import csv

#### HANDLING CSV FILES

#### GETTING DATA FROM CSV FILES

In [2]:
def add_full_name(full_path, new_full_path):
    master.to_csv(new_full_path)

In [3]:
if __name__ == "__main__":
    file_path="/home/camilo/Documents/Data_Science_Courses/Intro_to_Data_Science_Udacity/baseballdatabank-2017.1/core/Master.csv"
    new_file_path='/home/camilo/Documents/Data_Science_Courses/Intro_to_Data_Science_Udacity/baseballdatabank-2017.1/core/Master_full_name.csv'
    master=pd.read_csv(file_path)
    master['nameFull']=master['nameFirst'] + ' ' + master['nameLast']
    add_full_name(file_path, new_file_path)

/usr/local/lib/python2.7/dist-packages/pandas/core/computation/check.py:17: UserWarning: The installed version of numexpr 2.4.3 is not supported in pandas and will be not be used
The minimum supported version is 2.4.6

  ver=ver, min_ver=_MIN_NUMEXPR_VERSION), UserWarning)

In [4]:
master.head(5)

,playerID,birthYear,birthMonth,birthDay,birthCountry,birthState,birthCity,deathYear,deathMonth,deathDay,...,nameGiven,weight,height,bats,throws,debut,finalGame,retroID,bbrefID,nameFull
0,aardsda01,1981.0,12.0,27.0,USA,CO,Denver,NaN,NaN,NaN,...,David Allan,215.0,75.0,R,R,2004-04-06,2015-08-23,aardd001,aardsda01,David Aardsma
1,aaronha01,1934.0,2.0,5.0,USA,AL,Mobile,NaN,NaN,NaN,...,Henry Louis,180.0,72.0,R,R,1954-04-13,1976-10-03,aaroh101,aaronha01,Hank Aaron
2,aaronto01,1939.0,8.0,5.0,USA,AL,Mobile,1984.0,8.0,16.0,...,Tommie Lee,190.0,75.0,R,R,1962-04-10,1971-09-26,aarot101,aaronto01,Tommie Aaron
3,aasedo01,1954.0,9.0,8.0,USA,CA,Orange,NaN,NaN,NaN,...,Donald William,190.0,75.0,R,R,1977-07-26,1990-10-03,aased001,aasedo01,Don Aase
4,abadan01,1972.0,8.0,25.0,USA,FL,Palm Beach,NaN,NaN,NaN,...,Fausto Andres,184.0,73.0,L,L,2001-09-10,2006-04-13,abada001,abadan01,Andy Abad

#### WANGLING DATA USING SQL (RELATIONAL DATABASES)

#### Commands:
#select everything from the aadhaar data
SELECT * FROM Aadhaar_data;

#select the first 20 lines of the data
SELECT * FROM Aadhaar_data LIMIT 20;

#select columns district and subdisctrict from the data
SELECT district, subdistrict FROM Aadhaar_data LIMIT 20;

In [5]:
data = pd.read_csv('/home/camilo/Documents/Data_Science_Courses/Intro_to_Data_Science_Udacity/aadhaar_data.csv')

In [6]:
data.rename(columns = lambda x: x.replace(' ', '_').lower(), inplace=True)

In [7]:
data.head(10)

,registrar,enrolment_agency,state,district,sub_district,pin_code,gender,age,aadhaar_generated,enrolment_rejected,residents_providing_email,residents_providing_mobile_number
0,Allahabad Bank,Tera Software Ltd,Jharkhand,Ranchi,Namkum,834003,M,63,0,1,0,1
1,Allahabad Bank,Tera Software Ltd,Jharkhand,Ranchi,Ranchi,834004,F,36,0,1,0,1
2,Allahabad Bank,Vakrangee Softwares Limited,Gujarat,Surat,Nizar,394380,M,10,1,0,0,0
3,Allahabad Bank,Vakrangee Softwares Limited,Himachal Pradesh,Kangra,Baijnath,176081,M,44,1,0,1,1
4,Allahabad Bank,Vakrangee Softwares Limited,Madhya Pradesh,Chhindwara,Pandhurna,480334,M,35,1,0,0,0
5,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmadnagar,Nevasa,414105,M,28,1,0,0,0
6,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmadnagar,Rahta,413711,M,31,0,1,0,0
7,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmadnagar,Rahta,423107,F,9,0,1,0,0
8,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmadnagar,Rahta,423107,F,35,0,1,0,0
9,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmadnagar,Rahta,423107,M,33,0,1,0,1

In [8]:
sqldf('SELECT * FROM data LIMIT 50;', globals())

,registrar,enrolment_agency,state,district,sub_district,pin_code,gender,age,aadhaar_generated,enrolment_rejected,residents_providing_email,residents_providing_mobile_number
0,Allahabad Bank,Tera Software Ltd,Jharkhand,Ranchi,Namkum,834003,M,63,0,1,0,1
1,Allahabad Bank,Tera Software Ltd,Jharkhand,Ranchi,Ranchi,834004,F,36,0,1,0,1
2,Allahabad Bank,Vakrangee Softwares Limited,Gujarat,Surat,Nizar,394380,M,10,1,0,0,0
3,Allahabad Bank,Vakrangee Softwares Limited,Himachal Pradesh,Kangra,Baijnath,176081,M,44,1,0,1,1
4,Allahabad Bank,Vakrangee Softwares Limited,Madhya Pradesh,Chhindwara,Pandhurna,480334,M,35,1,0,0,0
5,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmadnagar,Nevasa,414105,M,28,1,0,0,0
6,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmadnagar,Rahta,413711,M,31,0,1,0,0
7,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmadnagar,Rahta,423107,F,9,0,1,0,0
8,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmadnagar,Rahta,423107,F,35,0,1,0,0
9,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmadnagar,Rahta,423107,M,33,0,1,0,1
10,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmadnagar,Rahta,423107,M,56,0,1,0,0
11,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmadnagar,Rahta,423107,M,64,0,1,0,0
12,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmadnagar,Rahuri,413706,F,55,0,1,0,0
13,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmadnagar,Rahuri,413715,F,31,0,1,0,0
14,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmadnagar,Rahuri,413715,F,35,0,1,0,0
15,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmadnagar,Rahuri,413715,F,49,0,1,0,0
16,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmadnagar,Rahuri,413715,F,65,0,1,0,0
17,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmadnagar,Rahuri,413715,M,19,0,1,0,0
18,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmadnagar,Rahuri,413715,M,22,0,1,0,0
19,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmadnagar,Rahuri,413715,M,47,0,1,0,0
20,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmadnagar,Rahuri,413715,M,65,0,1,0,0
21,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmadnagar,Sangamner,413714,F,28,0,1,0,1
22,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmed Nagar,Karjat,414402,F,19,0,1,0,0
23,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmed Nagar,Kopargaon,413708,F,10,0,1,0,1
24,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmed Nagar,Kopargaon,413708,F,14,0,1,0,1
25,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmed Nagar,Kopargaon,413708,F,15,0,1,0,0
26,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmed Nagar,Kopargaon,413708,F,16,0,1,0,0
27,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmed Nagar,Kopargaon,413708,F,17,0,1,0,0
28,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmed Nagar,Kopargaon,413708,F,20,0,1,0,0
29,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmed Nagar,Kopargaon,413708,F,23,0,1,0,0
30,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmed Nagar,Kopargaon,413708,F,28,0,2,0,1
31,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmed Nagar,Kopargaon,413708,F,30,0,1,0,0
32,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmed Nagar,Kopargaon,413708,F,37,0,1,0,0
33,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmed Nagar,Kopargaon,413708,F,39,0,1,0,0
34,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmed Nagar,Kopargaon,413708,F,45,0,1,0,1
35,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmed Nagar,Kopargaon,413708,F,68,0,1,0,0
36,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmed Nagar,Kopargaon,413708,M,12,0,1,0,0
37,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmed Nagar,Kopargaon,413708,M,13,0,3,0,0
38,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmed Nagar,Kopargaon,413708,M,15,0,1,0,1
39,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmed Nagar,Kopargaon,413708,M,17,0,1,0,1
40,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmed Nagar,Kopargaon,413708,M,20,0,1,0,0
41,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmed Nagar,Kopargaon,413708,M,22,0,1,1,1
42,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmed Nagar,Kopargaon,413708,M,23,0,1,0,0
43,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmed Nagar,Kopargaon,413708,M,27,0,1,0,1
44,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmed Nagar,Kopargaon,413708,M,38,0,1,0,0
45,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmed Nagar,Kopargaon,413708,M,40,0,1,0,0
46,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmed Nagar,Kopargaon,413708,M,43,0,1,0,1
47,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmed Nagar,Kopargaon,413708,M,44,0,1,0,0
48,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmed Nagar,Kopargaon,413708,M,46,0,1,0,0
49,Allahabad Bank,Vakrangee Softwares Limited,Maharashtra,Ahmed Nagar,Kopargaon,413708,M,53,0,1,0,0

In [9]:
sqldf('SELECT registrar, enrolment_agency FROM data LIMIT 50', globals())

         registrar             enrolment_agency
0   Allahabad Bank            Tera Software Ltd
1   Allahabad Bank            Tera Software Ltd
2   Allahabad Bank  Vakrangee Softwares Limited
3   Allahabad Bank  Vakrangee Softwares Limited
4   Allahabad Bank  Vakrangee Softwares Limited
5   Allahabad Bank  Vakrangee Softwares Limited
6   Allahabad Bank  Vakrangee Softwares Limited
7   Allahabad Bank  Vakrangee Softwares Limited
8   Allahabad Bank  Vakrangee Softwares Limited
9   Allahabad Bank  Vakrangee Softwares Limited
10  Allahabad Bank  Vakrangee Softwares Limited
11  Allahabad Bank  Vakrangee Softwares Limited
12  Allahabad Bank  Vakrangee Softwares Limited
13  Allahabad Bank  Vakrangee Softwares Limited
14  Allahabad Bank  Vakrangee Softwares Limited
15  Allahabad Bank  Vakrangee Softwares Limited
16  Allahabad Bank  Vakrangee Softwares Limited
17  Allahabad Bank  Vakrangee Softwares Limited
18  Allahabad Bank  Vakrangee Softwares Limited
19  Allahabad Bank  Vakrangee Softwares Limited
20  Allahabad Bank  Vakrangee Softwares Limited
21  Allahabad Bank  Vakrangee Softwares Limited
22  Allahabad Bank  Vakrangee Softwares Limited
23  Allahabad Bank  Vakrangee Softwares Limited
24  Allahabad Bank  Vakrangee Softwares Limited
25  Allahabad Bank  Vakrangee Softwares Limited
26  Allahabad Bank  Vakrangee Softwares Limited
27  Allahabad Bank  Vakrangee Softwares Limited
28  Allahabad Bank  Vakrangee Softwares Limited
29  Allahabad Bank  Vakrangee Softwares Limited
30  Allahabad Bank  Vakrangee Softwares Limited
31  Allahabad Bank  Vakrangee Softwares Limited
32  Allahabad Bank  Vakrangee Softwares Limited
33  Allahabad Bank  Vakrangee Softwares Limited
34  Allahabad Bank  Vakrangee Softwares Limited
35  Allahabad Bank  Vakrangee Softwares Limited
36  Allahabad Bank  Vakrangee Softwares Limited
37  Allahabad Bank  Vakrangee Softwares Limited
38  Allahabad Bank  Vakrangee Softwares Limited
39  Allahabad Bank  Vakrangee Softwares Limited
40  Allahabad Bank  Vakrangee Softwares Limited
41  Allahabad Bank  Vakrangee Softwares Limited
42  Allahabad Bank  Vakrangee Softwares Limited
43  Allahabad Bank  Vakrangee Softwares Limited
44  Allahabad Bank  Vakrangee Softwares Limited
45  Allahabad Bank  Vakrangee Softwares Limited
46  Allahabad Bank  Vakrangee Softwares Limited
47  Allahabad Bank  Vakrangee Softwares Limited
48  Allahabad Bank  Vakrangee Softwares Limited
49  Allahabad Bank  Vakrangee Softwares Limited

In [10]:
sqldf("SELECT * FROM data WHERE state='Gujarat'", globals())

,registrar,enrolment_agency,state,district,sub_district,pin_code,gender,age,aadhaar_generated,enrolment_rejected,residents_providing_email,residents_providing_mobile_number
0,Allahabad Bank,Vakrangee Softwares Limited,Gujarat,Surat,Nizar,394380,M,10,1,0,0,0
1,Bank Of India,CHESSY CONSULTANTS PVT LTD,Gujarat,Ahmedabad,Ahmadabad City,380050,F,61,1,0,0,1
2,Bank Of India,CHESSY CONSULTANTS PVT LTD,Gujarat,Amreli,Rajula,365560,F,34,1,0,0,1
3,Bank Of India,CHESSY CONSULTANTS PVT LTD,Gujarat,Amreli,Rajula,365560,M,38,1,0,0,1
4,Bank Of India,CHESSY CONSULTANTS PVT LTD,Gujarat,Junagadh,Patan Veraval,362268,F,35,1,0,0,1
5,Bank Of India,CHESSY CONSULTANTS PVT LTD,Gujarat,Kachchh,Rapar,370145,M,9,1,0,0,1
6,Bank Of India,CHESSY CONSULTANTS PVT LTD,Gujarat,Kachchh,Rapar,370165,M,20,1,0,0,1
7,Bank Of India,Frontech Systems Pvt Ltd,Gujarat,Junagadh,Kodinar,362720,M,25,1,0,0,1
8,Bank Of India,Frontech Systems Pvt Ltd,Gujarat,Surendra Nagar,Sayla,363430,F,27,1,0,0,1
9,Bank Of India,MANTRA SOFTTECH (INDIA) PVTLTD,Gujarat,Ahmedabad,Ahmadabad City,380004,M,7,1,0,0,1
10,Bank Of India,MANTRA SOFTTECH (INDIA) PVTLTD,Gujarat,Ahmedabad,Ahmadabad City,380061,F,23,0,1,0,1
11,Bank Of India,MANTRA SOFTTECH (INDIA) PVTLTD,Gujarat,Ahmedabad,Daskroi,380059,M,48,1,0,0,0
12,Bank Of India,MANTRA SOFTTECH (INDIA) PVTLTD,Gujarat,Amreli,Amreli,365601,F,44,1,0,0,1
13,Bank Of India,Matrix Processing House,Gujarat,Ahmedabad,Ahmadabad City,382475,M,45,1,0,0,1
14,Bank Of India,Matrix Processing House,Gujarat,Jamnagar,Dhrol,361001,F,26,1,0,0,1
15,Bank Of India,Matrix Processing House,Gujarat,Jamnagar,Dhrol,361130,F,26,1,0,0,1
16,Bank Of India,Matrix Processing House,Gujarat,Jamnagar,Dhrol,361130,M,29,1,0,0,1
17,Bank Of India,Matrix Processing House,Gujarat,Jamnagar,Jamjodhpur,360515,F,26,1,0,0,1
18,Bank Of India,Matrix Processing House,Gujarat,Jamnagar,Jodiya,361011,F,5,1,0,0,0
19,Bank Of India,Matrix Processing House,Gujarat,Jamnagar,Jodiya,361011,F,27,1,0,0,1
20,Bank Of India,Matrix Processing House,Gujarat,Jamnagar,Jodiya,361011,M,29,1,0,0,1
21,Bank Of India,Matrix Processing House,Gujarat,Jamnagar,Kalyanpur,361320,M,21,1,0,0,1
22,Bank Of India,Matrix Processing House,Gujarat,Kachchh,Mandvi,370455,M,20,1,0,0,1
23,Bank Of India,Matrix Processing House,Gujarat,Kachchh,Mundra,370410,M,6,1,0,0,1
24,Bank Of India,Matrix Processing House,Gujarat,Kachchh,Mundra,370410,M,34,1,0,0,1
25,Bank Of India,Matrix Processing House,Gujarat,Rajkot,Morvi,363642,F,26,1,0,0,1
26,Bank Of India,Matrix Processing House,Gujarat,Rajkot,Morvi,363642,M,33,1,0,0,1
27,Bank Of India,Matrix Processing House,Gujarat,Rajkot,Paddhari,360110,M,31,1,0,0,1
28,Bank Of India,Matrix Processing House,Gujarat,Surendra Nagar,Chotila,363520,M,29,1,0,0,1
29,Bank Of India,Matrix Processing House,Gujarat,Surendra Nagar,Limbdi,363421,F,32,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
55,Bank of Maharashtra,Alankit Finsec Ltd,Gujarat,Valsad,Pardi,396191,M,20,0,1,0,1
56,Bank of Maharashtra,Alankit Finsec Ltd,Gujarat,Valsad,Pardi,396191,M,23,1,0,0,1
57,Bank of Maharashtra,Alankit Finsec Ltd,Gujarat,Valsad,Pardi,396191,M,26,1,0,0,1
58,Bank of Maharashtra,Alankit Finsec Ltd,Gujarat,Valsad,Pardi,396191,M,31,1,0,0,1
59,Bank of Maharashtra,Alankit Finsec Ltd,Gujarat,Valsad,Pardi,396191,M,35,1,0,0,1
60,Bank of Maharashtra,Alankit Finsec Ltd,Gujarat,Valsad,Pardi,396193,M,8,1,0,0,1
61,Bank of Maharashtra,Alankit Finsec Ltd,Gujarat,Valsad,Pardi,396193,M,11,1,0,0,1
62,Bank of Maharashtra,Alankit Finsec Ltd,Gujarat,Valsad,Pardi,396193,M,50,1,0,0,1
63,Bank of Maharashtra,Alankit Finsec Ltd,Gujarat,Valsad,Pardi,396195,F,37,1,0,0,1
64,Bank of Maharashtra,Alankit Finsec Ltd,Gujarat,Valsad,Pardi,396195,M,11,1,0,0,1
65,Bank of Maharashtra,Alankit Finsec Ltd,Gujarat,Valsad,Pardi,396195,M,16,1,0,0,1
66,Bank of Maharashtra,Alankit Finsec Ltd,Gujarat,Valsad,Pardi,396195,M,21,1,0,0,0
67,Bank of Maharashtra,Alankit Finsec Ltd,Gujarat,Valsad,Pardi,396195,M,27,1,0,0,1
68,Bank of Maharashtra,Alankit Finsec Ltd,Gujarat,Valsad,Umbergaon,396155,F,31,1,0,0,1
69,Bank of Maharashtra,Micro Technologies India Ltd,Gujarat,Banaskantha,Danta,385120,F,25,1,0,0,1
70,Bank of Maharashtra,Micro Technologies India Ltd,Gujarat,Valsad,Pardi,396191,M,56,1,0,0,1
71,Bank of Maharashtra,Micro Technologies India Ltd,Gujarat,Valsad,Pardi,396191,M,62,1,0,0,1
72,CSC e-Governance Services India Limited,A I Soc for Electronics and Comp Tech,Gujarat,Ahmedabad,Ahmadabad City,380016,M,29,1,0,0,1
73,CSC e-Governance Services India Limited,A I Soc for Electronics and Comp Tech,Gujarat,Bharuch,Anklesvar,392011,M,59,1,0,0,1
74,CSC e-Governance Services India Limited,A I Soc for Electronics and Comp Tech,Gujarat,Vadodara,Padra,390016,M,29,1,0,0,1
75,CSC e-Governance Services India Limited,CMS Computers Ltd,Gujarat,Valsad,Pardi,396195,M,22,1,0,0,1
76,CSC e-Governance Services India Limited,Vakrangee Softwares Limited,Gujarat,Ahmedabad,Ahmadabad City,380015,F,50,1,0,0,1
77,Central Bank of India,CALANCE SOFTWARE PRIVATE LTD,Gujarat,Vadodara,Padra,390012,F,9,1,0,0,1
78,Central Bank of India,CALANCE SOFTWARE PRIVATE LTD,Gujarat,Vadodara,Padra,390012,F,36,1,0,0,1
79,Central Bank of India,CALANCE SOFTWARE PRIVATE LTD,Gujarat,Vadodara,Padra,390012,M,12,1,0,0,1
80,Central Bank of India,IAP COMPANY Pvt. Ltd,Gujarat,Banaskantha,Palanpur,385001,F,8,1,0,0,1
81,Central Bank of India,IAP COMPANY Pvt. Ltd,Gujarat,Banaskantha,Palanpur,385001,F,13,1,0,0,1
82,Central Bank of India,IAP COMPANY Pvt. Ltd,Gujarat,Banaskantha,Vadgam,385210,M,30,1,0,0,1
83,Central Bank of India,IAP COMPANY Pvt. Ltd,Gujarat,Kachchh,Rapar,370165,M,26,1,0,0,1
84,Central Bank of India,IAP COMPANY Pvt. Ltd,Gujarat,Patan,Sidhpur,384151,F,12,1,0,0,1

In [11]:
sqldf("SELECT district, sum(aadhaar_generated) FROM data GROUP BY district", globals())

            district  sum(aadhaar_generated)
0           Adilabad                       1
1               Agra                       9
2         Ahmadnagar                     552
3        Ahmed Nagar                       0
4          Ahmedabad                       9
5              Ajmer                     527
6              Akola                      55
7          Alappuzha                       1
8            Aligarh                       7
9          Alirajpur                    2965
10         Allahabad                     137
11            Almora                       8
12             Alwar                     303
13            Ambala                      70
14    Ambedkar Nagar                      13
15            Amethi                       1
16          Amravati                      11
17            Amreli                       4
18          Amritsar                     269
19            Amroha                       7
20        Ananthapur                       5
21             Angul                       5
22           Anuppur                    1938
23            Araria                       3
24             Arwal                       6
25       Ashok Nagar                      72
26           Auraiya                      10
27        Aurangabad                     533
28          Azamgarh                      16
29          Bagalkot                      33
..               ...                     ...
498           Ujjain                     913
499           Umaria                    1992
500              Una                      56
501          Unakoti                       6
502            Unnao                       2
503   Uttar Dinajpur                       2
504   Uttara Kannada                      10
505         Vadodara                       4
506         Vaishali                      16
507           Valsad                      30
508         Varanasi                      13
509          Vellore                       8
510          Vidisha                     887
511       Viluppuram                      85
512     Virudhunagar                       5
513    Visakhapatnam                       6
514     Vizianagaram                       5
515         Warangal                       4
516           Wardha                       8
517           Washim                     282
518   West Champaran                       9
519       West Delhi                     157
520  West Garo Hills                       1
521    West Godavari                       4
522       West Siang                       1
523   West Singhbhum                    4170
524     West Tripura                     392
525           Yadgir                      69
526     Yamuna Nagar                    1586
527         Yavatmal                     469

[528 rows x 2 columns]

In [12]:
sqldf("SELECT district, sub_district, sum(aadhaar_generated) FROM data GROUP BY district, sub_district", globals())

            district          sub_district  sum(aadhaar_generated)
0           Adilabad            Lokeswaram                       1
1               Agra                   Bah                       3
2               Agra              Etmadpur                       1
3               Agra             Fatehabad                       1
4               Agra             Kheragarh                       2
5               Agra               Kiraoli                       2
6         Ahmadnagar                 Akola                       3
7         Ahmadnagar               Jamkhed                       2
8         Ahmadnagar                Karjat                       3
9         Ahmadnagar             Kopargaon                       4
10        Ahmadnagar                 Nagar                       4
11        Ahmadnagar                Nevasa                     139
12        Ahmadnagar                Parner                       5
13        Ahmadnagar              Pathardi                     114
14        Ahmadnagar                 Rahta                       1
15        Ahmadnagar                Rahuri                     123
16        Ahmadnagar             Sangamner                       2
17        Ahmadnagar              Shevgaon                     120
18        Ahmadnagar             Shrigonda                      32
19       Ahmed Nagar                Karjat                       0
20       Ahmed Nagar             Kopargaon                       0
21       Ahmed Nagar                 Nagar                       0
22       Ahmed Nagar              Pathardi                       0
23       Ahmed Nagar                 Rahta                       0
24       Ahmed Nagar                Rahuri                       0
25         Ahmedabad        Ahmadabad City                       8
26         Ahmedabad               Daskroi                       1
27             Ajmer                 Ajmer                       1
28             Ajmer                Beawar                      29
29             Ajmer                Bhinay                      19
...              ...                   ...                     ...
2440  West Singhbhum              Majhgaon                     289
2441  West Singhbhum              Manjhari                       1
2442  West Singhbhum            Manoharpur                     227
2443  West Singhbhum  Noamundi (barajamda)                     827
2444  West Singhbhum                 Sonua                     109
2445  West Singhbhum             Tantnagar                       7
2446  West Singhbhum                 Tonto                     406
2447    West Tripura        Agartala Sadar                     112
2448    West Tripura                 Dukli                      24
2449    West Tripura              Hezamara                      42
2450    West Tripura               Jirania                     101
2451    West Tripura                Mandai                      44
2452    West Tripura              Mohanpur                      69
2453          Yadgir               Shahpur                      42
2454          Yadgir              Shorapur                      25
2455          Yadgir                Yadgir                       2
2456    Yamuna Nagar          Chhachhrauli                     148
2457    Yamuna Nagar              Jagadhri                    1438
2458        Yavatmal                  Arni                      13
2459        Yavatmal             Babulgaon                      49
2460        Yavatmal                Digras                       4
2461        Yavatmal              Ghatanji                      43
2462        Yavatmal                Kalamb                     189
2463        Yavatmal               Kelapur                       9
2464        Yavatmal              Mahagaon                      36
2465        Yavatmal                 Pusad                      33
2466        Yavatmal              Ralegaon                      24
2467        Yavatmal              Umarkhed                      34
2468        Yavatmal              Yavatmal                      34
2469        Yavatmal           Zari-Jamani                       1

[2470 rows x 3 columns]

In [13]:
sqldf("SELECT district, sub_district, sum(aadhaar_generated) FROM data WHERE age>60 GROUP BY district, sub_district", globals())

           district          sub_district  sum(aadhaar_generated)
0        Ahmadnagar                 Nagar                       0
1        Ahmadnagar                Nevasa                      18
2        Ahmadnagar                Parner                       1
3        Ahmadnagar              Pathardi                      13
4        Ahmadnagar                 Rahta                       0
5        Ahmadnagar                Rahuri                       5
6        Ahmadnagar              Shevgaon                      23
7        Ahmadnagar             Shrigonda                       3
8       Ahmed Nagar             Kopargaon                       0
9       Ahmed Nagar                 Nagar                       0
10        Ahmedabad        Ahmadabad City                       1
11            Ajmer                Beawar                       3
12            Ajmer                Bhinay                       1
13            Ajmer                 Kekri                      17
14            Ajmer            Kishangarh                       3
15            Ajmer             Peesangan                       1
16            Ajmer                Sarwar                      16
17            Akola               Balapur                       2
18            Akola               Telhara                       1
19        Alirajpur                Bhavra                      32
20        Alirajpur                 Jobat                      16
21        Allahabad             Allahabad                       9
22        Allahabad                  Bara                       1
23        Allahabad                Koraon                       1
24            Alwar                 Alwar                       1
25            Alwar                Behror                       5
26            Alwar              Kathumar                       1
27            Alwar        Kishangarh Bas                       6
28            Alwar              Kotkasim                       1
29            Alwar               Rajgarh                       0
..              ...                   ...                     ...
879  West Singhbhum         Chakradharpur                      15
880  West Singhbhum              Goilkera                       8
881  West Singhbhum          Jagannathpur                      26
882  West Singhbhum             Jhinkpani                       2
883  West Singhbhum             Khuntpani                      13
884  West Singhbhum            Kumardungi                      14
885  West Singhbhum              Majhgaon                      12
886  West Singhbhum            Manoharpur                       9
887  West Singhbhum  Noamundi (barajamda)                      37
888  West Singhbhum                 Sonua                      10
889  West Singhbhum             Tantnagar                       0
890  West Singhbhum                 Tonto                      16
891    West Tripura        Agartala Sadar                       6
892    West Tripura                 Dukli                       1
893    West Tripura              Hezamara                       2
894    West Tripura               Jirania                       6
895    West Tripura              Mohanpur                       2
896          Yadgir               Shahpur                       9
897    Yamuna Nagar          Chhachhrauli                      12
898    Yamuna Nagar              Jagadhri                     131
899        Yavatmal                  Arni                       2
900        Yavatmal             Babulgaon                      11
901        Yavatmal                Digras                       0
902        Yavatmal              Ghatanji                       3
903        Yavatmal                Kalamb                      24
904        Yavatmal              Mahagaon                       5
905        Yavatmal                 Pusad                       2
906        Yavatmal              Ralegaon                       1
907        Yavatmal              Umarkhed                       6
908        Yavatmal              Yavatmal                       3

[909 rows x 3 columns]

### WRANGLING DATA USING WEBSITES APIs

Many companies allow users and developers to access their data directly in a simple machine readyble format. They do through an Aplication Programming Interface API. There are different APIs, but one of the most common is REPRESENTATIONAL STATE TRANSFER or REST API.

GETTING DATA FROM THE API

In [14]:
import requests
import json

This is an URL query from the website last.fm with all the parameters needed. After the questionmark ? you see all the API parameters

http://ws.audioscrobbler.com/2.0/?method=album.getinfo&api_key=4beab33cc6d65b05800d51f5e83bde1b&artist=rihanna&album=unapologetic&format=json

In [15]:
url='http://ws.audioscrobbler.com/2.0/?method=geo.gettopartists&country=Spain&api_key=4beab33cc6d65b05800d51f5e83bde1b&format=json'

In [16]:
#JSON OBJECT
data=requests.get(url).text

In [17]:
data

u'{"topartists":{"artist":[{"name":"David Bowie","listeners":"3260367","mbid":"5441c29d-3602-4898-b1a1-b77fa23b8e50","url":"https://www.last.fm/music/David+Bowie","streamable":"0","image":[{"#text":"https://lastfm-img2.akamaized.net/i/u/34s/c7324cdbc5d76ed5e15f19b6e5099a2b.png","size":"small"},{"#text":"https://lastfm-img2.akamaized.net/i/u/64s/c7324cdbc5d76ed5e15f19b6e5099a2b.png","size":"medium"},{"#text":"https://lastfm-img2.akamaized.net/i/u/174s/c7324cdbc5d76ed5e15f19b6e5099a2b.png","size":"large"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/c7324cdbc5d76ed5e15f19b6e5099a2b.png","size":"extralarge"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/c7324cdbc5d76ed5e15f19b6e5099a2b.png","size":"mega"}]},{"name":"Radiohead","listeners":"4640197","mbid":"a74b1b7f-71a5-4011-9441-d0b5e4122711","url":"https://www.last.fm/music/Radiohead","streamable":"0","image":[{"#text":"https://lastfm-img2.akamaized.net/i/u/34s/9b109fcab6c48f5714c8554a31ab9943.png","size":"small"},{"#text":"https://lastfm-img2.akamaized.net/i/u/64s/9b109fcab6c48f5714c8554a31ab9943.png","size":"medium"},{"#text":"https://lastfm-img2.akamaized.net/i/u/174s/9b109fcab6c48f5714c8554a31ab9943.png","size":"large"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/9b109fcab6c48f5714c8554a31ab9943.png","size":"extralarge"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/9b109fcab6c48f5714c8554a31ab9943.png","size":"mega"}]},{"name":"Coldplay","listeners":"5276075","mbid":"cc197bad-dc9c-440d-a5b5-d52ba2e14234","url":"https://www.last.fm/music/Coldplay","streamable":"0","image":[{"#text":"https://lastfm-img2.akamaized.net/i/u/34s/76b29fb461e74a48bab4686e0269421b.png","size":"small"},{"#text":"https://lastfm-img2.akamaized.net/i/u/64s/76b29fb461e74a48bab4686e0269421b.png","size":"medium"},{"#text":"https://lastfm-img2.akamaized.net/i/u/174s/76b29fb461e74a48bab4686e0269421b.png","size":"large"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/76b29fb461e74a48bab4686e0269421b.png","size":"extralarge"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/76b29fb461e74a48bab4686e0269421b.png","size":"mega"}]},{"name":"Queen","listeners":"3864974","mbid":"420ca290-76c5-41af-999e-564d7c71f1a7","url":"https://www.last.fm/music/Queen","streamable":"0","image":[{"#text":"https://lastfm-img2.akamaized.net/i/u/34s/1e122948db5a40e6b1a6220f18309bfb.png","size":"small"},{"#text":"https://lastfm-img2.akamaized.net/i/u/64s/1e122948db5a40e6b1a6220f18309bfb.png","size":"medium"},{"#text":"https://lastfm-img2.akamaized.net/i/u/174s/1e122948db5a40e6b1a6220f18309bfb.png","size":"large"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/1e122948db5a40e6b1a6220f18309bfb.png","size":"extralarge"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/1e122948db5a40e6b1a6220f18309bfb.png","size":"mega"}]},{"name":"The Rolling Stones","listeners":"3712678","mbid":"b071f9fa-14b0-4217-8e97-eb41da73f598","url":"https://www.last.fm/music/The+Rolling+Stones","streamable":"0","image":[{"#text":"https://lastfm-img2.akamaized.net/i/u/34s/6e7eac3310bbf128cbae2c4c17443849.png","size":"small"},{"#text":"https://lastfm-img2.akamaized.net/i/u/64s/6e7eac3310bbf128cbae2c4c17443849.png","size":"medium"},{"#text":"https://lastfm-img2.akamaized.net/i/u/174s/6e7eac3310bbf128cbae2c4c17443849.png","size":"large"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/6e7eac3310bbf128cbae2c4c17443849.png","size":"extralarge"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/6e7eac3310bbf128cbae2c4c17443849.png","size":"mega"}]},{"name":"Muse","listeners":"4012478","mbid":"fd857293-5ab8-40de-b29e-55a69d4e4d0f","url":"https://www.last.fm/music/Muse","streamable":"0","image":[{"#text":"https://lastfm-img2.akamaized.net/i/u/34s/0f95cfbc16eab2b4a4ebffc531690b75.png","size":"small"},{"#text":"https://lastfm-img2.akamaized.net/i/u/64s/0f95cfbc16eab2b4a4ebffc531690b75.png","size":"medium"},{"#text":"https://lastfm-img2.akamaized.net/i/u/174s/0f95cfbc16eab2b4a4ebffc531690b75.png","size":"large"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/0f95cfbc16eab2b4a4ebffc531690b75.png","size":"extralarge"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/0f95cfbc16eab2b4a4ebffc531690b75.png","size":"mega"}]},{"name":"The Beatles","listeners":"3562311","mbid":"b10bbbfc-cf9e-42e0-be17-e2c3e1d2600d","url":"https://www.last.fm/music/The+Beatles","streamable":"0","image":[{"#text":"https://lastfm-img2.akamaized.net/i/u/34s/ed22a42245c941c190aca4b6cda19c0d.png","size":"small"},{"#text":"https://lastfm-img2.akamaized.net/i/u/64s/ed22a42245c941c190aca4b6cda19c0d.png","size":"medium"},{"#text":"https://lastfm-img2.akamaized.net/i/u/174s/ed22a42245c941c190aca4b6cda19c0d.png","size":"large"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/ed22a42245c941c190aca4b6cda19c0d.png","size":"extralarge"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/ed22a42245c941c190aca4b6cda19c0d.png","size":"mega"}]},{"name":"Daft Punk","listeners":"3699044","mbid":"056e4f3e-d505-4dad-8ec1-d04f521cbb56","url":"https://www.last.fm/music/Daft+Punk","streamable":"0","image":[{"#text":"https://lastfm-img2.akamaized.net/i/u/34s/9fd718d4c80e4ac89107c6c0bb908440.png","size":"small"},{"#text":"https://lastfm-img2.akamaized.net/i/u/64s/9fd718d4c80e4ac89107c6c0bb908440.png","size":"medium"},{"#text":"https://lastfm-img2.akamaized.net/i/u/174s/9fd718d4c80e4ac89107c6c0bb908440.png","size":"large"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/9fd718d4c80e4ac89107c6c0bb908440.png","size":"extralarge"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/9fd718d4c80e4ac89107c6c0bb908440.png","size":"mega"}]},{"name":"Arctic Monkeys","listeners":"3395167","mbid":"ada7a83c-e3e1-40f1-93f9-3e73dbc9298a","url":"https://www.last.fm/music/Arctic+Monkeys","streamable":"0","image":[{"#text":"https://lastfm-img2.akamaized.net/i/u/34s/177100db6181b9a73e2c7ea87c83b252.png","size":"small"},{"#text":"https://lastfm-img2.akamaized.net/i/u/64s/177100db6181b9a73e2c7ea87c83b252.png","size":"medium"},{"#text":"https://lastfm-img2.akamaized.net/i/u/174s/177100db6181b9a73e2c7ea87c83b252.png","size":"large"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/177100db6181b9a73e2c7ea87c83b252.png","size":"extralarge"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/177100db6181b9a73e2c7ea87c83b252.png","size":"mega"}]},{"name":"The Cure","listeners":"2855384","mbid":"69ee3720-a7cb-4402-b48d-a02c366f2bcf","url":"https://www.last.fm/music/The+Cure","streamable":"0","image":[{"#text":"https://lastfm-img2.akamaized.net/i/u/34s/0adefe283018c0b7a743f6c1149fc54e.png","size":"small"},{"#text":"https://lastfm-img2.akamaized.net/i/u/64s/0adefe283018c0b7a743f6c1149fc54e.png","size":"medium"},{"#text":"https://lastfm-img2.akamaized.net/i/u/174s/0adefe283018c0b7a743f6c1149fc54e.png","size":"large"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/0adefe283018c0b7a743f6c1149fc54e.png","size":"extralarge"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/0adefe283018c0b7a743f6c1149fc54e.png","size":"mega"}]},{"name":"Sia","listeners":"2009884","mbid":"2f548675-008d-4332-876c-108b0c7ab9c5","url":"https://www.last.fm/music/Sia","streamable":"0","image":[{"#text":"https://lastfm-img2.akamaized.net/i/u/34s/c3a980e3cc236681edeaa373c22c53d2.png","size":"small"},{"#text":"https://lastfm-img2.akamaized.net/i/u/64s/c3a980e3cc236681edeaa373c22c53d2.png","size":"medium"},{"#text":"https://lastfm-img2.akamaized.net/i/u/174s/c3a980e3cc236681edeaa373c22c53d2.png","size":"large"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/c3a980e3cc236681edeaa373c22c53d2.png","size":"extralarge"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/c3a980e3cc236681edeaa373c22c53d2.png","size":"mega"}]},{"name":"Red Hot Chili Peppers","listeners":"4525016","mbid":"8bfac288-ccc5-448d-9573-c33ea2aa5c30","url":"https://www.last.fm/music/Red+Hot+Chili+Peppers","streamable":"0","image":[{"#text":"https://lastfm-img2.akamaized.net/i/u/34s/2bcc8f4f83fd408296983e8eaddce0e4.png","size":"small"},{"#text":"https://lastfm-img2.akamaized.net/i/u/64s/2bcc8f4f83fd408296983e8eaddce0e4.png","size":"medium"},{"#text":"https://lastfm-img2.akamaized.net/i/u/174s/2bcc8f4f83fd408296983e8eaddce0e4.png","size":"large"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/2bcc8f4f83fd408296983e8eaddce0e4.png","size":"extralarge"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/2bcc8f4f83fd408296983e8eaddce0e4.png","size":"mega"}]},{"name":"Blur","listeners":"2805406","mbid":"ba853904-ae25-4ebb-89d6-c44cfbd71bd2","url":"https://www.last.fm/music/Blur","streamable":"0","image":[{"#text":"https://lastfm-img2.akamaized.net/i/u/34s/313950bfa7164d70a5aba38b3baa5e4e.png","size":"small"},{"#text":"https://lastfm-img2.akamaized.net/i/u/64s/313950bfa7164d70a5aba38b3baa5e4e.png","size":"medium"},{"#text":"https://lastfm-img2.akamaized.net/i/u/174s/313950bfa7164d70a5aba38b3baa5e4e.png","size":"large"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/313950bfa7164d70a5aba38b3baa5e4e.png","size":"extralarge"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/313950bfa7164d70a5aba38b3baa5e4e.png","size":"mega"}]},{"name":"Ed Sheeran","listeners":"1514256","mbid":"b8a7c51f-362c-4dcb-a259-bc6e0095f0a6","url":"https://www.last.fm/music/Ed+Sheeran","streamable":"0","image":[{"#text":"https://lastfm-img2.akamaized.net/i/u/34s/71ab2582b79a456787bf08b6e419f0dc.png","size":"small"},{"#text":"https://lastfm-img2.akamaized.net/i/u/64s/71ab2582b79a456787bf08b6e419f0dc.png","size":"medium"},{"#text":"https://lastfm-img2.akamaized.net/i/u/174s/71ab2582b79a456787bf08b6e419f0dc.png","size":"large"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/71ab2582b79a456787bf08b6e419f0dc.png","size":"extralarge"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/71ab2582b79a456787bf08b6e419f0dc.png","size":"mega"}]},{"name":"Adele","listeners":"2773006","mbid":"cc2c9c3c-b7bc-4b8b-84d8-4fbd8779e493","url":"https://www.last.fm/music/Adele","streamable":"0","image":[{"#text":"https://lastfm-img2.akamaized.net/i/u/34s/f684afedf6e81a941d8d403c5f5c20be.png","size":"small"},{"#text":"https://lastfm-img2.akamaized.net/i/u/64s/f684afedf6e81a941d8d403c5f5c20be.png","size":"medium"},{"#text":"https://lastfm-img2.akamaized.net/i/u/174s/f684afedf6e81a941d8d403c5f5c20be.png","size":"large"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/f684afedf6e81a941d8d403c5f5c20be.png","size":"extralarge"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/f684afedf6e81a941d8d403c5f5c20be.png","size":"mega"}]},{"name":"Nirvana","listeners":"4176635","mbid":"9282c8b4-ca0b-4c6b-b7e3-4f7762dfc4d6","url":"https://www.last.fm/music/Nirvana","streamable":"0","image":[{"#text":"https://lastfm-img2.akamaized.net/i/u/34s/89a490f578e4451b9dea9c20158c8a1e.png","size":"small"},{"#text":"https://lastfm-img2.akamaized.net/i/u/64s/89a490f578e4451b9dea9c20158c8a1e.png","size":"medium"},{"#text":"https://lastfm-img2.akamaized.net/i/u/174s/89a490f578e4451b9dea9c20158c8a1e.png","size":"large"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/89a490f578e4451b9dea9c20158c8a1e.png","size":"extralarge"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/89a490f578e4451b9dea9c20158c8a1e.png","size":"mega"}]},{"name":"Pink Floyd","listeners":"2989063","mbid":"83d91898-7763-47d7-b03b-b92132375c47","url":"https://www.last.fm/music/Pink+Floyd","streamable":"0","image":[{"#text":"https://lastfm-img2.akamaized.net/i/u/34s/98d2ca11cd6642519d750f4b82fbec2c.png","size":"small"},{"#text":"https://lastfm-img2.akamaized.net/i/u/64s/98d2ca11cd6642519d750f4b82fbec2c.png","size":"medium"},{"#text":"https://lastfm-img2.akamaized.net/i/u/174s/98d2ca11cd6642519d750f4b82fbec2c.png","size":"large"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/98d2ca11cd6642519d750f4b82fbec2c.png","size":"extralarge"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/98d2ca11cd6642519d750f4b82fbec2c.png","size":"mega"}]},{"name":"Tame Impala","listeners":"1025748","mbid":"63aa26c3-d59b-4da4-84ac-716b54f1ef4d","url":"https://www.last.fm/music/Tame+Impala","streamable":"0","image":[{"#text":"https://lastfm-img2.akamaized.net/i/u/34s/fea673d784afe1837d58015177f726f3.png","size":"small"},{"#text":"https://lastfm-img2.akamaized.net/i/u/64s/fea673d784afe1837d58015177f726f3.png","size":"medium"},{"#text":"https://lastfm-img2.akamaized.net/i/u/174s/fea673d784afe1837d58015177f726f3.png","size":"large"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/fea673d784afe1837d58015177f726f3.png","size":"extralarge"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/fea673d784afe1837d58015177f726f3.png","size":"mega"}]},{"name":"The xx","listeners":"1862873","mbid":"c5c2ea1c-4bde-4f4d-bd0b-47b200bf99d6","url":"https://www.last.fm/music/The+xx","streamable":"0","image":[{"#text":"https://lastfm-img2.akamaized.net/i/u/34s/c6e4f9cf07018a5f6b800d29f4b0b3d4.png","size":"small"},{"#text":"https://lastfm-img2.akamaized.net/i/u/64s/c6e4f9cf07018a5f6b800d29f4b0b3d4.png","size":"medium"},{"#text":"https://lastfm-img2.akamaized.net/i/u/174s/c6e4f9cf07018a5f6b800d29f4b0b3d4.png","size":"large"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/c6e4f9cf07018a5f6b800d29f4b0b3d4.png","size":"extralarge"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/c6e4f9cf07018a5f6b800d29f4b0b3d4.png","size":"mega"}]},{"name":"Bob Dylan","listeners":"2599011","mbid":"72c536dc-7137-4477-a521-567eeb840fa8","url":"https://www.last.fm/music/Bob+Dylan","streamable":"0","image":[{"#text":"https://lastfm-img2.akamaized.net/i/u/34s/c71c48ac1745438f8915a108ef77dc4d.png","size":"small"},{"#text":"https://lastfm-img2.akamaized.net/i/u/64s/c71c48ac1745438f8915a108ef77dc4d.png","size":"medium"},{"#text":"https://lastfm-img2.akamaized.net/i/u/174s/c71c48ac1745438f8915a108ef77dc4d.png","size":"large"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/c71c48ac1745438f8915a108ef77dc4d.png","size":"extralarge"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/c71c48ac1745438f8915a108ef77dc4d.png","size":"mega"}]},{"name":"Arcade Fire","listeners":"2506673","mbid":"52074ba6-e495-4ef3-9bb4-0703888a9f68","url":"https://www.last.fm/music/Arcade+Fire","streamable":"0","image":[{"#text":"https://lastfm-img2.akamaized.net/i/u/34s/3a49cff89e545ef8de758284f8aebab5.png","size":"small"},{"#text":"https://lastfm-img2.akamaized.net/i/u/64s/3a49cff89e545ef8de758284f8aebab5.png","size":"medium"},{"#text":"https://lastfm-img2.akamaized.net/i/u/174s/3a49cff89e545ef8de758284f8aebab5.png","size":"large"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/3a49cff89e545ef8de758284f8aebab5.png","size":"extralarge"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/3a49cff89e545ef8de758284f8aebab5.png","size":"mega"}]},{"name":"Major Lazer","listeners":"1152601","mbid":"75be165a-ad83-4d12-bd28-f589a15c479f","url":"https://www.last.fm/music/Major+Lazer","streamable":"0","image":[{"#text":"https://lastfm-img2.akamaized.net/i/u/34s/2ef42dd356169dee318e0ce819769b55.png","size":"small"},{"#text":"https://lastfm-img2.akamaized.net/i/u/64s/2ef42dd356169dee318e0ce819769b55.png","size":"medium"},{"#text":"https://lastfm-img2.akamaized.net/i/u/174s/2ef42dd356169dee318e0ce819769b55.png","size":"large"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/2ef42dd356169dee318e0ce819769b55.png","size":"extralarge"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/2ef42dd356169dee318e0ce819769b55.png","size":"mega"}]},{"name":"The Weeknd","listeners":"1161148","mbid":"c8b03190-306c-4120-bb0b-6f2ebfc06ea9","url":"https://www.last.fm/music/The+Weeknd","streamable":"0","image":[{"#text":"https://lastfm-img2.akamaized.net/i/u/34s/5e2ae8b921286cae40d5e68f3cdfcd57.png","size":"small"},{"#text":"https://lastfm-img2.akamaized.net/i/u/64s/5e2ae8b921286cae40d5e68f3cdfcd57.png","size":"medium"},{"#text":"https://lastfm-img2.akamaized.net/i/u/174s/5e2ae8b921286cae40d5e68f3cdfcd57.png","size":"large"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/5e2ae8b921286cae40d5e68f3cdfcd57.png","size":"extralarge"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/5e2ae8b921286cae40d5e68f3cdfcd57.png","size":"mega"}]},{"name":"Calvin Harris","listeners":"2072403","mbid":"8dd98bdc-80ec-4e93-8509-2f46bafc09a7","url":"https://www.last.fm/music/Calvin+Harris","streamable":"0","image":[{"#text":"https://lastfm-img2.akamaized.net/i/u/34s/bb48d7e1401bbdf0d5f999f5abded34e.png","size":"small"},{"#text":"https://lastfm-img2.akamaized.net/i/u/64s/bb48d7e1401bbdf0d5f999f5abded34e.png","size":"medium"},{"#text":"https://lastfm-img2.akamaized.net/i/u/174s/bb48d7e1401bbdf0d5f999f5abded34e.png","size":"large"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/bb48d7e1401bbdf0d5f999f5abded34e.png","size":"extralarge"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/bb48d7e1401bbdf0d5f999f5abded34e.png","size":"mega"}]},{"name":"The Strokes","listeners":"3192210","mbid":"f181961b-20f7-459e-89de-920ef03c7ed0","url":"https://www.last.fm/music/The+Strokes","streamable":"0","image":[{"#text":"https://lastfm-img2.akamaized.net/i/u/34s/88ce8ff517534fe2b269b62e1f4b9bd0.png","size":"small"},{"#text":"https://lastfm-img2.akamaized.net/i/u/64s/88ce8ff517534fe2b269b62e1f4b9bd0.png","size":"medium"},{"#text":"https://lastfm-img2.akamaized.net/i/u/174s/88ce8ff517534fe2b269b62e1f4b9bd0.png","size":"large"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/88ce8ff517534fe2b269b62e1f4b9bd0.png","size":"extralarge"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/88ce8ff517534fe2b269b62e1f4b9bd0.png","size":"mega"}]},{"name":"U2","listeners":"3420312","mbid":"a3cb23fc-acd3-4ce0-8f36-1e5aa6a18432","url":"https://www.last.fm/music/U2","streamable":"0","image":[{"#text":"https://lastfm-img2.akamaized.net/i/u/34s/9fe2c7365f01339ab533bfaa9e79cac7.png","size":"small"},{"#text":"https://lastfm-img2.akamaized.net/i/u/64s/9fe2c7365f01339ab533bfaa9e79cac7.png","size":"medium"},{"#text":"https://lastfm-img2.akamaized.net/i/u/174s/9fe2c7365f01339ab533bfaa9e79cac7.png","size":"large"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/9fe2c7365f01339ab533bfaa9e79cac7.png","size":"extralarge"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/9fe2c7365f01339ab533bfaa9e79cac7.png","size":"mega"}]},{"name":"Rihanna","listeners":"4438636","mbid":"db36a76f-4cdf-43ac-8cd0-5e48092d2bae","url":"https://www.last.fm/music/Rihanna","streamable":"0","image":[{"#text":"https://lastfm-img2.akamaized.net/i/u/34s/a4d22128fd3f8b3f1f8b6d626cc34c57.png","size":"small"},{"#text":"https://lastfm-img2.akamaized.net/i/u/64s/a4d22128fd3f8b3f1f8b6d626cc34c57.png","size":"medium"},{"#text":"https://lastfm-img2.akamaized.net/i/u/174s/a4d22128fd3f8b3f1f8b6d626cc34c57.png","size":"large"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/a4d22128fd3f8b3f1f8b6d626cc34c57.png","size":"extralarge"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/a4d22128fd3f8b3f1f8b6d626cc34c57.png","size":"mega"}]},{"name":"Foo Fighters","listeners":"3938786","mbid":"67f66c07-6e61-4026-ade5-7e782fad3a5d","url":"https://www.last.fm/music/Foo+Fighters","streamable":"0","image":[{"#text":"https://lastfm-img2.akamaized.net/i/u/34s/162a4a04d9d14d2e90b651e8c076decb.png","size":"small"},{"#text":"https://lastfm-img2.akamaized.net/i/u/64s/162a4a04d9d14d2e90b651e8c076decb.png","size":"medium"},{"#text":"https://lastfm-img2.akamaized.net/i/u/174s/162a4a04d9d14d2e90b651e8c076decb.png","size":"large"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/162a4a04d9d14d2e90b651e8c076decb.png","size":"extralarge"},{"#text":"https://lastfm-img2.akamaized.net/i/u/300x300/162a4a04d9d14d2e90b651e8c076decb.png","size":"mega"}]},{"name":"Depeche Mode","listeners":"2619651","mbid":"8538e728-ca0b-4321-b7e5-cff6565dd4c0","url":"https://www.last.fm/music/Depeche+Mode","streamable":"0","image":[{"#text":"https://lastfm-img2.akamaized.net/i/u/34s/c5c16bdadd8e4f13a061511863909

In [18]:
#CONVERT THE JSON DATA TO A PYTHON DICTIONARY
data=json.loads(data)

In [19]:
data

{u'topartists': {u'@attr': {u'country': u'Spain',
   u'page': u'1',
   u'perPage': u'50',
   u'total': u'595215',
   u'totalPages': u'11905'},
  u'artist': [{u'image': [{u'#text': u'https://lastfm-img2.akamaized.net/i/u/34s/c7324cdbc5d76ed5e15f19b6e5099a2b.png',
      u'size': u'small'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/64s/c7324cdbc5d76ed5e15f19b6e5099a2b.png',
      u'size': u'medium'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/174s/c7324cdbc5d76ed5e15f19b6e5099a2b.png',
      u'size': u'large'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/c7324cdbc5d76ed5e15f19b6e5099a2b.png',
      u'size': u'extralarge'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/c7324cdbc5d76ed5e15f19b6e5099a2b.png',
      u'size': u'mega'}],
    u'listeners': u'3260367',
    u'mbid': u'5441c29d-3602-4898-b1a1-b77fa23b8e50',
    u'name': u'David Bowie',
    u'streamable': u'0',
    u'url': u'https://www.last.fm/music/David+Bowie'},
   {u'image': [{u'#text': u'https://lastfm-img2.akamaized.net/i/u/34s/9b109fcab6c48f5714c8554a31ab9943.png',
      u'size': u'small'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/64s/9b109fcab6c48f5714c8554a31ab9943.png',
      u'size': u'medium'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/174s/9b109fcab6c48f5714c8554a31ab9943.png',
      u'size': u'large'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/9b109fcab6c48f5714c8554a31ab9943.png',
      u'size': u'extralarge'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/9b109fcab6c48f5714c8554a31ab9943.png',
      u'size': u'mega'}],
    u'listeners': u'4640197',
    u'mbid': u'a74b1b7f-71a5-4011-9441-d0b5e4122711',
    u'name': u'Radiohead',
    u'streamable': u'0',
    u'url': u'https://www.last.fm/music/Radiohead'},
   {u'image': [{u'#text': u'https://lastfm-img2.akamaized.net/i/u/34s/76b29fb461e74a48bab4686e0269421b.png',
      u'size': u'small'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/64s/76b29fb461e74a48bab4686e0269421b.png',
      u'size': u'medium'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/174s/76b29fb461e74a48bab4686e0269421b.png',
      u'size': u'large'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/76b29fb461e74a48bab4686e0269421b.png',
      u'size': u'extralarge'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/76b29fb461e74a48bab4686e0269421b.png',
      u'size': u'mega'}],
    u'listeners': u'5276075',
    u'mbid': u'cc197bad-dc9c-440d-a5b5-d52ba2e14234',
    u'name': u'Coldplay',
    u'streamable': u'0',
    u'url': u'https://www.last.fm/music/Coldplay'},
   {u'image': [{u'#text': u'https://lastfm-img2.akamaized.net/i/u/34s/1e122948db5a40e6b1a6220f18309bfb.png',
      u'size': u'small'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/64s/1e122948db5a40e6b1a6220f18309bfb.png',
      u'size': u'medium'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/174s/1e122948db5a40e6b1a6220f18309bfb.png',
      u'size': u'large'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/1e122948db5a40e6b1a6220f18309bfb.png',
      u'size': u'extralarge'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/1e122948db5a40e6b1a6220f18309bfb.png',
      u'size': u'mega'}],
    u'listeners': u'3864974',
    u'mbid': u'420ca290-76c5-41af-999e-564d7c71f1a7',
    u'name': u'Queen',
    u'streamable': u'0',
    u'url': u'https://www.last.fm/music/Queen'},
   {u'image': [{u'#text': u'https://lastfm-img2.akamaized.net/i/u/34s/6e7eac3310bbf128cbae2c4c17443849.png',
      u'size': u'small'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/64s/6e7eac3310bbf128cbae2c4c17443849.png',
      u'size': u'medium'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/174s/6e7eac3310bbf128cbae2c4c17443849.png',
      u'size': u'large'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/6e7eac3310bbf128cbae2c4c17443849.png',
      u'size': u'extralarge'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/6e7eac3310bbf128cbae2c4c17443849.png',
      u'size': u'mega'}],
    u'listeners': u'3712678',
    u'mbid': u'b071f9fa-14b0-4217-8e97-eb41da73f598',
    u'name': u'The Rolling Stones',
    u'streamable': u'0',
    u'url': u'https://www.last.fm/music/The+Rolling+Stones'},
   {u'image': [{u'#text': u'https://lastfm-img2.akamaized.net/i/u/34s/0f95cfbc16eab2b4a4ebffc531690b75.png',
      u'size': u'small'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/64s/0f95cfbc16eab2b4a4ebffc531690b75.png',
      u'size': u'medium'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/174s/0f95cfbc16eab2b4a4ebffc531690b75.png',
      u'size': u'large'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/0f95cfbc16eab2b4a4ebffc531690b75.png',
      u'size': u'extralarge'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/0f95cfbc16eab2b4a4ebffc531690b75.png',
      u'size': u'mega'}],
    u'listeners': u'4012478',
    u'mbid': u'fd857293-5ab8-40de-b29e-55a69d4e4d0f',
    u'name': u'Muse',
    u'streamable': u'0',
    u'url': u'https://www.last.fm/music/Muse'},
   {u'image': [{u'#text': u'https://lastfm-img2.akamaized.net/i/u/34s/ed22a42245c941c190aca4b6cda19c0d.png',
      u'size': u'small'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/64s/ed22a42245c941c190aca4b6cda19c0d.png',
      u'size': u'medium'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/174s/ed22a42245c941c190aca4b6cda19c0d.png',
      u'size': u'large'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/ed22a42245c941c190aca4b6cda19c0d.png',
      u'size': u'extralarge'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/ed22a42245c941c190aca4b6cda19c0d.png',
      u'size': u'mega'}],
    u'listeners': u'3562311',
    u'mbid': u'b10bbbfc-cf9e-42e0-be17-e2c3e1d2600d',
    u'name': u'The Beatles',
    u'streamable': u'0',
    u'url': u'https://www.last.fm/music/The+Beatles'},
   {u'image': [{u'#text': u'https://lastfm-img2.akamaized.net/i/u/34s/9fd718d4c80e4ac89107c6c0bb908440.png',
      u'size': u'small'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/64s/9fd718d4c80e4ac89107c6c0bb908440.png',
      u'size': u'medium'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/174s/9fd718d4c80e4ac89107c6c0bb908440.png',
      u'size': u'large'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/9fd718d4c80e4ac89107c6c0bb908440.png',
      u'size': u'extralarge'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/9fd718d4c80e4ac89107c6c0bb908440.png',
      u'size': u'mega'}],
    u'listeners': u'3699044',
    u'mbid': u'056e4f3e-d505-4dad-8ec1-d04f521cbb56',
    u'name': u'Daft Punk',
    u'streamable': u'0',
    u'url': u'https://www.last.fm/music/Daft+Punk'},
   {u'image': [{u'#text': u'https://lastfm-img2.akamaized.net/i/u/34s/177100db6181b9a73e2c7ea87c83b252.png',
      u'size': u'small'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/64s/177100db6181b9a73e2c7ea87c83b252.png',
      u'size': u'medium'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/174s/177100db6181b9a73e2c7ea87c83b252.png',
      u'size': u'large'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/177100db6181b9a73e2c7ea87c83b252.png',
      u'size': u'extralarge'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/177100db6181b9a73e2c7ea87c83b252.png',
      u'size': u'mega'}],
    u'listeners': u'3395167',
    u'mbid': u'ada7a83c-e3e1-40f1-93f9-3e73dbc9298a',
    u'name': u'Arctic Monkeys',
    u'streamable': u'0',
    u'url': u'https://www.last.fm/music/Arctic+Monkeys'},
   {u'image': [{u'#text': u'https://lastfm-img2.akamaized.net/i/u/34s/0adefe283018c0b7a743f6c1149fc54e.png',
      u'size': u'small'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/64s/0adefe283018c0b7a743f6c1149fc54e.png',
      u'size': u'medium'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/174s/0adefe283018c0b7a743f6c1149fc54e.png',
      u'size': u'large'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/0adefe283018c0b7a743f6c1149fc54e.png',
      u'size': u'extralarge'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/0adefe283018c0b7a743f6c1149fc54e.png',
      u'size': u'mega'}],
    u'listeners': u'2855384',
    u'mbid': u'69ee3720-a7cb-4402-b48d-a02c366f2bcf',
    u'name': u'The Cure',
    u'streamable': u'0',
    u'url': u'https://www.last.fm/music/The+Cure'},
   {u'image': [{u'#text': u'https://lastfm-img2.akamaized.net/i/u/34s/c3a980e3cc236681edeaa373c22c53d2.png',
      u'size': u'small'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/64s/c3a980e3cc236681edeaa373c22c53d2.png',
      u'size': u'medium'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/174s/c3a980e3cc236681edeaa373c22c53d2.png',
      u'size': u'large'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/c3a980e3cc236681edeaa373c22c53d2.png',
      u'size': u'extralarge'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/c3a980e3cc236681edeaa373c22c53d2.png',
      u'size': u'mega'}],
    u'listeners': u'2009884',
    u'mbid': u'2f548675-008d-4332-876c-108b0c7ab9c5',
    u'name': u'Sia',
    u'streamable': u'0',
    u'url': u'https://www.last.fm/music/Sia'},
   {u'image': [{u'#text': u'https://lastfm-img2.akamaized.net/i/u/34s/2bcc8f4f83fd408296983e8eaddce0e4.png',
      u'size': u'small'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/64s/2bcc8f4f83fd408296983e8eaddce0e4.png',
      u'size': u'medium'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/174s/2bcc8f4f83fd408296983e8eaddce0e4.png',
      u'size': u'large'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/2bcc8f4f83fd408296983e8eaddce0e4.png',
      u'size': u'extralarge'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/2bcc8f4f83fd408296983e8eaddce0e4.png',
      u'size': u'mega'}],
    u'listeners': u'4525016',
    u'mbid': u'8bfac288-ccc5-448d-9573-c33ea2aa5c30',
    u'name': u'Red Hot Chili Peppers',
    u'streamable': u'0',
    u'url': u'https://www.last.fm/music/Red+Hot+Chili+Peppers'},
   {u'image': [{u'#text': u'https://lastfm-img2.akamaized.net/i/u/34s/313950bfa7164d70a5aba38b3baa5e4e.png',
      u'size': u'small'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/64s/313950bfa7164d70a5aba38b3baa5e4e.png',
      u'size': u'medium'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/174s/313950bfa7164d70a5aba38b3baa5e4e.png',
      u'size': u'large'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/313950bfa7164d70a5aba38b3baa5e4e.png',
      u'size': u'extralarge'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/313950bfa7164d70a5aba38b3baa5e4e.png',
      u'size': u'mega'}],
    u'listeners': u'2805406',
    u'mbid': u'ba853904-ae25-4ebb-89d6-c44cfbd71bd2',
    u'name': u'Blur',
    u'streamable': u'0',
    u'url': u'https://www.last.fm/music/Blur'},
   {u'image': [{u'#text': u'https://lastfm-img2.akamaized.net/i/u/34s/71ab2582b79a456787bf08b6e419f0dc.png',
      u'size': u'small'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/64s/71ab2582b79a456787bf08b6e419f0dc.png',
      u'size': u'medium'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/174s/71ab2582b79a456787bf08b6e419f0dc.png',
      u'size': u'large'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/71ab2582b79a456787bf08b6e419f0dc.png',
      u'size': u'extralarge'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/71ab2582b79a456787bf08b6e419f0dc.png',
      u'size': u'mega'}],
    u'listeners': u'1514256',
    u'mbid': u'b8a7c51f-362c-4dcb-a259-bc6e0095f0a6',
    u'name': u'Ed Sheeran',
    u'streamable': u'0',
    u'url': u'https://www.last.fm/music/Ed+Sheeran'},
   {u'image': [{u'#text': u'https://lastfm-img2.akamaized.net/i/u/34s/f684afedf6e81a941d8d403c5f5c20be.png',
      u'size': u'small'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/64s/f684afedf6e81a941d8d403c5f5c20be.png',
      u'size': u'medium'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/174s/f684afedf6e81a941d8d403c5f5c20be.png',
      u'size': u'large'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/f684afedf6e81a941d8d403c5f5c20be.png',
      u'size': u'extralarge'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/f684afedf6e81a941d8d403c5f5c20be.png',
      u'size': u'mega'}],
    u'listeners': u'2773006',
    u'mbid': u'cc2c9c3c-b7bc-4b8b-84d8-4fbd8779e493',
    u'name': u'Adele',
    u'streamable': u'0',
    u'url': u'https://www.last.fm/music/Adele'},
   {u'image': [{u'#text': u'https://lastfm-img2.akamaized.net/i/u/34s/89a490f578e4451b9dea9c20158c8a1e.png',
      u'size': u'small'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/64s/89a490f578e4451b9dea9c20158c8a1e.png',
      u'size': u'medium'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/174s/89a490f578e4451b9dea9c20158c8a1e.png',
      u'size': u'large'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/89a490f578e4451b9dea9c20158c8a1e.png',
      u'size': u'extralarge'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/89a490f578e4451b9dea9c20158c8a1e.png',
      u'size': u'mega'}],
    u'listeners': u'4176635',
    u'mbid': u'9282c8b4-ca0b-4c6b-b7e3-4f7762dfc4d6',
    u'name': u'Nirvana',
    u'streamable': u'0',
    u'url': u'https://www.last.fm/music/Nirvana'},
   {u'image': [{u'#text': u'https://lastfm-img2.akamaized.net/i/u/34s/98d2ca11cd6642519d750f4b82fbec2c.png',
      u'size': u'small'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/64s/98d2ca11cd6642519d750f4b82fbec2c.png',
      u'size': u'medium'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/174s/98d2ca11cd6642519d750f4b82fbec2c.png',
      u'size': u'large'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/98d2ca11cd6642519d750f4b82fbec2c.png',
      u'size': u'extralarge'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/98d2ca11cd6642519d750f4b82fbec2c.png',
      u'size': u'mega'}],
    u'listeners': u'2989063',
    u'mbid': u'83d91898-7763-47d7-b03b-b92132375c47',
    u'name': u'Pink Floyd',
    u'streamable': u'0',
    u'url': u'https://www.last.fm/music/Pink+Floyd'},
   {u'image': [{u'#text': u'https://lastfm-img2.akamaized.net/i/u/34s/fea673d784afe1837d58015177f726f3.png',
      u'size': u'small'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/64s/fea673d784afe1837d58015177f726f3.png',
      u'size': u'medium'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/174s/fea673d784afe1837d58015177f726f3.png',
      u'size': u'large'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/fea673d784afe1837d58015177f726f3.png',
      u'size': u'extralarge'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/fea673d784afe1837d58015177f726f3.png',
      u'size': u'mega'}],
    u'listeners': u'1025748',
    u'mbid': u'63aa26c3-d59b-4da4-84ac-716b54f1ef4d',
    u'name': u'Tame Impala',
    u'streamable': u'0',
    u'url': u'https://www.last.fm/music/Tame+Impala'},
   {u'image': [{u'#text': u'https://lastfm-img2.akamaized.net/i/u/34s/c6e4f9cf07018a5f6b800d29f4b0b3d4.png',
      u'size': u'small'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/64s/c6e4f9cf07018a5f6b800d29f4b0b3d4.png',
      u'size': u'medium'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/174s/c6e4f9cf07018a5f6b800d29f4b0b3d4.png',
      u'size': u'large'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/c6e4f9cf07018a5f6b800d29f4b0b3d4.png',
      u'size': u'extralarge'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/c6e4f9cf07018a5f6b800d29f4b0b3d4.png',
      u'size': u'mega'}],
    u'listeners': u'1862873',
    u'mbid': u'c5c2ea1c-4bde-4f4d-bd0b-47b200bf99d6',
    u'name': u'The xx',
    u'streamable': u'0',
    u'url': u'https://www.last.fm/music/The+xx'},
   {u'image': [{u'#text': u'https://lastfm-img2.akamaized.net/i/u/34s/c71c48ac1745438f8915a108ef77dc4d.png',
      u'size': u'small'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/64s/c71c48ac1745438f8915a108ef77dc4d.png',
      u'size': u'medium'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/174s/c71c48ac1745438f8915a108ef77dc4d.png',
      u'size': u'large'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/c71c48ac1745438f8915a108ef77dc4d.png',
      u'size': u'extralarge'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/c71c48ac1745438f8915a108ef77dc4d.png',
      u'size': u'mega'}],
    u'listeners': u'2599011',
    u'mbid': u'72c536dc-7137-4477-a521-567eeb840fa8',
    u'name': u'Bob Dylan',
    u'streamable': u'0',
    u'url': u'https://www.last.fm/music/Bob+Dylan'},
   {u'image': [{u'#text': u'https://lastfm-img2.akamaized.net/i/u/34s/3a49cff89e545ef8de758284f8aebab5.png',
      u'size': u'small'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/64s/3a49cff89e545ef8de758284f8aebab5.png',
      u'size': u'medium'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/174s/3a49cff89e545ef8de758284f8aebab5.png',
      u'size': u'large'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/3a49cff89e545ef8de758284f8aebab5.png',
      u'size': u'extralarge'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/3a49cff89e545ef8de758284f8aebab5.png',
      u'size': u'mega'}],
    u'listeners': u'2506673',
    u'mbid': u'52074ba6-e495-4ef3-9bb4-0703888a9f68',
    u'name': u'Arcade Fire',
    u'streamable': u'0',
    u'url': u'https://www.last.fm/music/Arcade+Fire'},
   {u'image': [{u'#text': u'https://lastfm-img2.akamaized.net/i/u/34s/2ef42dd356169dee318e0ce819769b55.png',
      u'size': u'small'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/64s/2ef42dd356169dee318e0ce819769b55.png',
      u'size': u'medium'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/174s/2ef42dd356169dee318e0ce819769b55.png',
      u'size': u'large'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/2ef42dd356169dee318e0ce819769b55.png',
      u'size': u'extralarge'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/2ef42dd356169dee318e0ce819769b55.png',
      u'size': u'mega'}],
    u'listeners': u'1152601',
    u'mbid': u'75be165a-ad83-4d12-bd28-f589a15c479f',
    u'name': u'Major Lazer',
    u'streamable': u'0',
    u'url': u'https://www.last.fm/music/Major+Lazer'},
   {u'image': [{u'#text': u'https://lastfm-img2.akamaized.net/i/u/34s/5e2ae8b921286cae40d5e68f3cdfcd57.png',
      u'size': u'small'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/64s/5e2ae8b921286cae40d5e68f3cdfcd57.png',
      u'size': u'medium'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/174s/5e2ae8b921286cae40d5e68f3cdfcd57.png',
      u'size': u'large'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/5e2ae8b921286cae40d5e68f3cdfcd57.png',
      u'size': u'extralarge'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/5e2ae8b921286cae40d5e68f3cdfcd57.png',
      u'size': u'mega'}],
    u'listeners': u'1161148',
    u'mbid': u'c8b03190-306c-4120-bb0b-6f2ebfc06ea9',
    u'name': u'The Weeknd',
    u'streamable': u'0',
    u'url': u'https://www.last.fm/music/The+Weeknd'},
   {u'image': [{u'#text': u'https://lastfm-img2.akamaized.net/i/u/34s/bb48d7e1401bbdf0d5f999f5abded34e.png',
      u'size': u'small'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/64s/bb48d7e1401bbdf0d5f999f5abded34e.png',
      u'size': u'medium'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/174s/bb48d7e1401bbdf0d5f999f5abded34e.png',
      u'size': u'large'},
     {u'#text': u'https://lastfm-img2.akamaized.net/i/u/300x300/bb48d7e1401bbdf0d5f999f5abded34e.png',
      u'size': u'extralarge'},

In [20]:
data['topartists']['artist'][0]['name']

u'David Bowie'

## WHICH METHODS CAN HELP TO DEAL WITH MISSING DATA?

#### PARTIAL DELETION: it means we limite the data we use for analysis to the data that we have available and we know is correct. It is divided into LISTWISE DELETION AND PAIRWISE DELETION.

#### LISTWISE DELETION means that the whole row is excluded for analysis.

#### PAIRWISE DELETION means that specific bad field of a row is excluded for analysis, but the good field is included for the analysis.

##### But sometimes we do not have enough data or there are scenarios where removing our missing values would compromisethe representativeness of our sample, it does not make sense to throw away a bunch of entries just because there are missing values. This could impact the statistical power of whatever analysis we try to do. In this case it makes sense to make an intelligent guess at the missing values in ou data. 

#### The process of approximating these missing values is called IMPUTATION.

There are different techniques of imputation. One of them is EASY IMPUTATION.

#### EASY IMPUTATION (CALCULATE MEAN OF THE COLUMN AND PUT IT IN THE CELLS WITH MISSING VALUES)
The good thing of this method is that we do not change the mean of the column. But if we are studying the relationship between the column where i applied EASY IMPUTATION  and another column, this method lessens the corelation between these two columns.

#### IMPUTE USING LINEAR REGRESSION
The general idea is that we create an equation that predicts missing values in our data, using imformation we do have, and then use that equation to fill in those missing values. The negative side effect of applying this technique is that we would over emphasize existing trends in the data. For example is there is a correlation between two columns, this method will amplify this trend. 

The two previous methods are the most simplistic ones. They are good but sometimes they can either attenaute or amplify preexisting trends in the data.

In [21]:
baseball=pd.read_csv('/home/camilo/Documents/Data_Science_Courses/Intro_to_Data_Science_Udacity/baseballdatabank-2017.1/core/Master.csv')

In [22]:
baseball.head(10)

,playerID,birthYear,birthMonth,birthDay,birthCountry,birthState,birthCity,deathYear,deathMonth,deathDay,...,nameLast,nameGiven,weight,height,bats,throws,debut,finalGame,retroID,bbrefID
0,aardsda01,1981.0,12.0,27.0,USA,CO,Denver,NaN,NaN,NaN,...,Aardsma,David Allan,215.0,75.0,R,R,2004-04-06,2015-08-23,aardd001,aardsda01
1,aaronha01,1934.0,2.0,5.0,USA,AL,Mobile,NaN,NaN,NaN,...,Aaron,Henry Louis,180.0,72.0,R,R,1954-04-13,1976-10-03,aaroh101,aaronha01
2,aaronto01,1939.0,8.0,5.0,USA,AL,Mobile,1984.0,8.0,16.0,...,Aaron,Tommie Lee,190.0,75.0,R,R,1962-04-10,1971-09-26,aarot101,aaronto01
3,aasedo01,1954.0,9.0,8.0,USA,CA,Orange,NaN,NaN,NaN,...,Aase,Donald William,190.0,75.0,R,R,1977-07-26,1990-10-03,aased001,aasedo01
4,abadan01,1972.0,8.0,25.0,USA,FL,Palm Beach,NaN,NaN,NaN,...,Abad,Fausto Andres,184.0,73.0,L,L,2001-09-10,2006-04-13,abada001,abadan01
5,abadfe01,1985.0,12.0,17.0,D.R.,La Romana,La Romana,NaN,NaN,NaN,...,Abad,Fernando Antonio,220.0,73.0,L,L,2010-07-28,2016-09-25,abadf001,abadfe01
6,abadijo01,1850.0,11.0,4.0,USA,PA,Philadelphia,1905.0,5.0,17.0,...,Abadie,John W.,192.0,72.0,R,R,1875-04-26,1875-06-10,abadj101,abadijo01
7,abbated01,1877.0,4.0,15.0,USA,PA,Latrobe,1957.0,1.0,6.0,...,Abbaticchio,Edward James,170.0,71.0,R,R,1897-09-04,1910-09-15,abbae101,abbated01
8,abbeybe01,1869.0,11.0,11.0,USA,VT,Essex,1962.0,6.0,11.0,...,Abbey,Bert Wood,175.0,71.0,R,R,1892-06-14,1896-09-23,abbeb101,abbeybe01
9,abbeych01,1866.0,10.0,14.0,USA,NE,Falls City,1926.0,4.0,27.0,...,Abbey,Charles S.,169.0,68.0,L,L,1893-08-16,1897-08-19,abbec101,abbeych01

In [23]:
baseball.weight.head(21)

0     215.0
1     180.0
2     190.0
3     190.0
4     184.0
5     220.0
6     192.0
7     170.0
8     175.0
9     169.0
10    190.0
11    180.0
12    200.0
13    190.0
14    200.0
15    180.0
16    200.0
17    180.0
18    185.0
19    195.0
20      NaN
Name: weight, dtype: float64

In [24]:
baseball[['weight']].apply(np.mean)

weight    186.375596
dtype: float64

In [25]:
baseball.weight.fillna(np.mean(baseball.weight))
#baseball.weight.fillna(np.mean(baseball[['weight']].apply(np.mean)))  ASI TAMBIEN FUNCIONA

0        215.000000
1        180.000000
2        190.000000
3        190.000000
4        184.000000
5        220.000000
6        192.000000
7        170.000000
8        175.000000
9        169.000000
10       190.000000
11       180.000000
12       200.000000
13       190.000000
14       200.000000
15       180.000000
16       200.000000
17       180.000000
18       185.000000
19       195.000000
20       186.375596
21       215.000000
22       190.000000
23       185.000000
24       210.000000
25       215.000000
26       170.000000
27       200.000000
28       200.000000
29       190.000000
            ...
19075    225.000000
19076    187.000000
19077    225.000000
19078    190.000000
19079    165.000000
19080    150.000000
19081    170.000000
19082    195.000000
19083    185.000000
19084    200.000000
19085    200.000000
19086    200.000000
19087    205.000000
19088    175.000000
19089    180.000000
19090    210.000000
19091    200.000000
19092    185.000000
19093    175.000000
19094    195.000000
19095    190.000000
19096    230.000000
19097    215.000000
19098    220.000000
19099    220.000000
19100    182.000000
19101    173.000000
19102    195.000000
19103    160.000000
19104    190.000000
Name: weight, Length: 19105, dtype: float64

### SOME QUIZES

Check out the number of rainy days.

In [26]:
path="/home/camilo/Documents/Data_Science_Courses/Intro_to_Data_Science_Udacity"
weather_data = pd.read_csv(path+'/weather_underground.csv')

In [27]:
q = 'SELECT COUNT(rain) FROM weather_data WHERE rain=1'

In [28]:
sqldf(q, locals())

   COUNT(rain)
0           10

Check out the foggy days (two groups, foggy 1 or not foggy 0) and outputs the max value of the maxtempi per each foggy group.

In [29]:
q = 'SELECT fog, MAX(maxtempi) FROM weather_data GROUP BY fog'

In [30]:
sqldf(q, locals())

   fog  MAX(maxtempi)
0    0             86
1    1             81

The SQL query should return one column and one row - the average meantempi on days that are a Saturday or Sunday (i.e., the the average mean temperature on weekends). The dataframe will be titled 'weather_data' and you can access the date in the dataframe via the 'date' column.

You might also find that interpreting numbers as integers or floats may not
work initially.  In order to get around this issue, it may be useful to cast
these numbers as integers.  This can be done by writing cast(column as integer).
So for example, if we wanted to cast the maxtempi column as an integer, we would actually
write something like where cast(maxtempi as integer) = 76, as opposed to simply 
where maxtempi = 76.

Also, you can convert dates to days of the week via the 'strftime' keyword in SQL.
For example, cast (strftime('%w', date) as integer) will return 0 if the date
is a Sunday or 6 if the date is a Saturday.

In [31]:
q='SELECT AVG(meantempi) FROM weather_data WHERE cast(strftime("%w", date) as integer)=6 or cast(strftime("%w", date) as integer)=0'

In [32]:
sqldf(q, locals())

   AVG(meantempi)
0       65.111111

More specifically you want to find the average
minimum temperature (mintempi column of the weather dataframe) on 
rainy days where the minimum temperature is greater than 55 degrees.

You might also find that interpreting numbers as integers or floats may not
work initially.  In order to get around this issue, it may be useful to cast
these numbers as integers.  This can be done by writing cast(column as integer).
So for example, if we wanted to cast the maxtempi column as an integer, we would actually
write something like where cast(maxtempi as integer) = 76, as opposed to simply 
where maxtempi = 76.

In [33]:
q='SELECT AVG(mintempi) FROM weather_data WHERE rain=1 and mintempi>55'

In [34]:
sqldf(q, locals())

   AVG(mintempi)
0          61.25

Filenames is a list of MTA Subway turnstile text files. A link to an example
MTA Subway turnstile text file can be seen at the URL below:
http://web.mta.info/developers/data/nyct/turnstile/turnstile_110507.txt

As you can see, there are numerous data points included in each row of the
a MTA Subway turnstile text file. 

You want to write a function that will update each row in the text
file so there is only one entry per row. A few examples below:
A002,R051,02-00-00,05-28-11,00:00:00,REGULAR,003178521,001100739
A002,R051,02-00-00,05-28-11,04:00:00,REGULAR,003178541,001100746
A002,R051,02-00-00,05-28-11,08:00:00,REGULAR,003178559,001100775

Write the updates to a different text file in the format of "updated_" + filename.
For example:
    1) if you read in a text file called "turnstile_110521.txt"
    2) you should write the updated data to "updated_turnstile_110521.txt"

In [35]:
list1=[]       
with open('turnstile-110528.txt', 'rb') as f:    
    reader=csv.reader(f)       
    for row in reader:
        for i in range(3,len(row),5):
            list1.append(row[0:3] + row[i:i+5])

with open("updated_turnstile-110528.txt", "wb") as f:
    writer = csv.writer(f)
    writer.writerows(list1)

Write a function that takes each file in the list files, which all have the 
columns 'C/A, UNIT, SCP, DATEn, TIMEn, DESCn, ENTRIESn, EXITSn', and consolidates
them into one file located at output_file.  There should be ONE row with the column
headers, located at the top of the file. The input files do not have column header
rows of their own.

For example, if file_1 has:
line 1 ...
line 2 ...

and another file, file_2 has:
line 3 ...
line 4 ...
line 5 ...

We need to combine file_1 and file_2 into a master_file like below:
 'C/A, UNIT, SCP, DATEn, TIMEn, DESCn, ENTRIESn, EXITSn'
line 1 ...
line 2 ...
line 3 ...
line 4 ...
line 5 ...

In [36]:
files=['lines1.csv', 'lines2.csv']

with open('output_file.csv', 'w') as master_file:
    master_file.write('C/A,UNIT,SCP,DATEn,TIMEn,DESCn,ENTRIESn,EXITSn\n')
    
ofile=open("output_file.csv", "a")

for f in files:
    ifile=open(f, "rb")
    for line in ifile:
        ofile.write(line)
        
ofile.close()

This function should read the csv file located at filename into a pandas dataframe,
    and filter the dataframe to only rows where the 'DESCn' column has the value 'REGULAR'.
    
    For example, if the pandas dataframe is as follows:
    ,C/A,UNIT,SCP,DATEn,TIMEn,DESCn,ENTRIESn,EXITSn
    0,A002,R051,02-00-00,05-01-11,00:00:00,REGULAR,3144312,1088151
    1,A002,R051,02-00-00,05-01-11,04:00:00,DOOR,3144335,1088159
    2,A002,R051,02-00-00,05-01-11,08:00:00,REGULAR,3144353,1088177
    3,A002,R051,02-00-00,05-01-11,12:00:00,DOOR,3144424,1088231
    
    The dataframe will look like below after filtering to only rows where DESCn column
    has the value 'REGULAR':
    0,A002,R051,02-00-00,05-01-11,00:00:00,REGULAR,3144312,1088151
    2,A002,R051,02-00-00,05-01-11,08:00:00,REGULAR,3144353,1088177

In [37]:
data1 = pd.read_csv('updated_turnstile-110528.txt')
data1.columns= ["C/A","UNIT","SCP","DATEn","TIMEn","DESCn","ENTRIESn","EXITSn"]

In [38]:
data1[data1['DESCn']=="REGULAR"]

       C/A  UNIT       SCP     DATEn     TIMEn    DESCn  ENTRIESn   EXITSn
0     A002  R051  02-00-00  05-21-11  04:00:00  REGULAR   3169415  1097588
1     A002  R051  02-00-00  05-21-11  08:00:00  REGULAR   3169431  1097607
2     A002  R051  02-00-00  05-21-11  12:00:00  REGULAR   3169506  1097686
3     A002  R051  02-00-00  05-21-11  16:00:00  REGULAR   3169693  1097734
4     A002  R051  02-00-00  05-21-11  20:00:00  REGULAR   3169998  1097769
5     A002  R051  02-00-00  05-22-11  00:00:00  REGULAR   3170119  1097792
6     A002  R051  02-00-00  05-22-11  04:00:00  REGULAR   3170146  1097801
7     A002  R051  02-00-00  05-22-11  08:00:00  REGULAR   3170164  1097820
8     A002  R051  02-00-00  05-22-11  12:00:00  REGULAR   3170240  1097867
9     A002  R051  02-00-00  05-22-11  16:00:00  REGULAR   3170388  1097912
10    A002  R051  02-00-00  05-22-11  20:00:00  REGULAR   3170611  1097941
11    A002  R051  02-00-00  05-23-11  00:00:00  REGULAR   3170695  1097964
12    A002  R051  02-00-00  05-23-11  04:00:00  REGULAR   3170701  1097964
13    A002  R051  02-00-00  05-23-11  08:00:00  REGULAR   3170746  1098069
14    A002  R051  02-00-00  05-23-11  12:00:00  REGULAR   3170897  1098378
15    A002  R051  02-00-00  05-23-11  16:00:00  REGULAR   3171194  1098447
16    A002  R051  02-00-00  05-23-11  20:00:00  REGULAR   3172059  1098511
17    A002  R051  02-00-00  05-24-11  00:00:00  REGULAR   3172200  1098528
18    A002  R051  02-00-00  05-24-11  04:00:00  REGULAR   3172214  1098529
19    A002  R051  02-00-00  05-24-11  08:00:00  REGULAR   3172266  1098628
20    A002  R051  02-00-00  05-24-11  12:00:00  REGULAR   3172407  1098952
21    A002  R051  02-00-00  05-24-11  16:00:00  REGULAR   3172689  1099010
22    A002  R051  02-00-00  05-24-11  20:00:00  REGULAR   3173590  1099055
23    A002  R051  02-00-00  05-25-11  00:00:00  REGULAR   3173803  1099079
24    A002  R051  02-00-00  05-25-11  04:00:00  REGULAR   3173826  1099081
25    A002  R051  02-00-00  05-25-11  08:00:00  REGULAR   3173873  1099178
26    A002  R051  02-00-00  05-25-11  12:00:00  REGULAR   3174022  1099496
27    A002  R051  02-00-00  05-25-11  16:00:00  REGULAR   3174309  1099572
28    A002  R051  02-00-00  05-25-11  20:00:00  REGULAR   3175172  1099651
29    A002  R051  02-00-00  05-26-11  00:00:00  REGULAR   3175360  1099675
...    ...   ...       ...       ...       ...      ...       ...      ...
7310  A042  R086  01-00-04  05-22-11  20:00:00  REGULAR    912511  4167549
7311  A042  R086  01-00-04  05-23-11  00:00:00  REGULAR    912606  4167828
7312  A042  R086  01-00-04  05-23-11  04:00:00  REGULAR    912616  4167855
7313  A042  R086  01-00-04  05-23-11  08:00:00  REGULAR    912622  4168025
7314  A042  R086  01-00-04  05-23-11  12:00:00  REGULAR    912679  4168923
7315  A042  R086  01-00-04  05-23-11  16:00:00  REGULAR    912843  4169719
7316  A042  R086  01-00-04  05-23-11  20:00:00  REGULAR    913194  4170521
7317  A042  R086  01-00-04  05-24-11  00:00:00  REGULAR    913291  4170682
7318  A042  R086  01-00-04  05-24-11  04:00:00  REGULAR    913300  4170711
7319  A042  R086  01-00-04  05-24-11  08:00:00  REGULAR    913309  4170890
7320  A042  R086  01-00-04  05-24-11  12:00:00  REGULAR    913360  4171856
7321  A042  R086  01-00-04  05-24-11  16:00:00  REGULAR    913536  4172582
7322  A042  R086  01-00-04  05-24-11  20:00:00  REGULAR    913892  4173464
7323  A042  R086  01-00-04  05-25-11  00:00:00  REGULAR    914006  4173624
7326  A042  R086  01-00-04  05-25-11  08:00:00  REGULAR    914027  4173813
7327  A042  R086  01-00-04  05-25-11  12:00:00  REGULAR    914087  4174759
7328  A042  R086  01-00-04  05-25-11  16:00:00  REGULAR    914262  4175544
7329  A042  R086  01-00-04  05-25-11  20:00:00  REGULAR    914686  4176445
7330  A042  R086  01-00-04  05-26-11  00:00:00  REGULAR    914808  4176633
7331  A042  R086  01-00-04  05-26-11  04:00:00  REGULAR    914822  4176664
7332  A042  R086  01-00-04  05-26-11  08:00:00  REGULAR    914830  4176849
7333  A042  R086  01-00-04  05-26-11  12:00:00  REGULAR    914902  4177778
7334  A042  R086  01-00-04  05-26-11  16:00:00  REGULAR    915105  4178603
7335  A042  R086  01-00-04  05-26-11  20:00:00  REGULAR    915583  4179421
7336  A042  R086  01-00-04  05-27-11  00:00:00  REGULAR    915724  4179647
7337  A042  R086  01-00-04  05-27-11  04:00:00  REGULAR    915737  4179675
7338  A042  R086  01-00-04  05-27-11  08:00:00  REGULAR    915743  4179820
7339  A042  R086  01-00-04  05-27-11  12:00:00  REGULAR    915806  4180746
7340  A042  R086  01-00-04  05-27-11  16:00:00  REGULAR    916090  4181746
7341  A042  R086  01-00-04  05-27-11  20:00:00  REGULAR    916517  4182631

[6182 rows x 8 columns]

In [39]:
upd=pd.read_csv('updated_turnstile-110528.txt', header=None) 
upd.columns=["C/A", "UNIT", "SCP", "DATEn", "TIMEn", "DESCn", "ENTRIESn", "EXITSn"]
upd.ENTRIESn.fillna(1)

s1=pd.Series([0]) # or s1=pd.Series([0],index=[-1]) # Create a serie begining in index -1, with only 1 value = 0
                  # s1=s1.append(upd.ENTRIESn) # Append the column ENTRIESn to the serie s1  
s1=s1.append(upd.ENTRIESn, ignore_index=True) 
s1=s1.drop(s1.index[len(s1)-1])  # Since it has one more row, i delete the last row

list1=[] # Create empty list

for i in range(0,len(upd.ENTRIESn),1):
    list1.append(upd.ENTRIESn[i]-s1[i])

#for i in range(0,len(upd.ENTRIESn),1): 
#    list1.append(upd.ENTRIESn[i]-s1[i-1]) # If index -1 was used.
# Subtract each value of the column ENTRIESn with the previous row and append the result to the list list1  
    
upd['ENTRIESn_hourly']=list1 # Assign the list1 to the new column ENTRIESn_hourly of the dataframe
        
#s3=pandas.Series([0]*7343, index=[range(0,7342)]) This is to create a serie of 7343 rows automatically

In [40]:
upd

,C/A,UNIT,SCP,DATEn,TIMEn,DESCn,ENTRIESn,EXITSn,ENTRIESn_hourly
0,A002,R051,02-00-00,05-21-11,00:00:00,REGULAR,3169391,1097585,3169391
1,A002,R051,02-00-00,05-21-11,04:00:00,REGULAR,3169415,1097588,24
2,A002,R051,02-00-00,05-21-11,08:00:00,REGULAR,3169431,1097607,16
3,A002,R051,02-00-00,05-21-11,12:00:00,REGULAR,3169506,1097686,75
4,A002,R051,02-00-00,05-21-11,16:00:00,REGULAR,3169693,1097734,187
5,A002,R051,02-00-00,05-21-11,20:00:00,REGULAR,3169998,1097769,305
6,A002,R051,02-00-00,05-22-11,00:00:00,REGULAR,3170119,1097792,121
7,A002,R051,02-00-00,05-22-11,04:00:00,REGULAR,3170146,1097801,27
8,A002,R051,02-00-00,05-22-11,08:00:00,REGULAR,3170164,1097820,18
9,A002,R051,02-00-00,05-22-11,12:00:00,REGULAR,3170240,1097867,76
10,A002,R051,02-00-00,05-22-11,16:00:00,REGULAR,3170388,1097912,148
11,A002,R051,02-00-00,05-22-11,20:00:00,REGULAR,3170611,1097941,223
12,A002,R051,02-00-00,05-23-11,00:00:00,REGULAR,3170695,1097964,84
13,A002,R051,02-00-00,05-23-11,04:00:00,REGULAR,3170701,1097964,6
14,A002,R051,02-00-00,05-23-11,08:00:00,REGULAR,3170746,1098069,45
15,A002,R051,02-00-00,05-23-11,12:00:00,REGULAR,3170897,1098378,151
16,A002,R051,02-00-00,05-23-11,16:00:00,REGULAR,3171194,1098447,297
17,A002,R051,02-00-00,05-23-11,20:00:00,REGULAR,3172059,1098511,865
18,A002,R051,02-00-00,05-24-11,00:00:00,REGULAR,3172200,1098528,141
19,A002,R051,02-00-00,05-24-11,04:00:00,REGULAR,3172214,1098529,14
20,A002,R051,02-00-00,05-24-11,08:00:00,REGULAR,3172266,1098628,52
21,A002,R051,02-00-00,05-24-11,12:00:00,REGULAR,3172407,1098952,141
22,A002,R051,02-00-00,05-24-11,16:00:00,REGULAR,3172689,1099010,282
23,A002,R051,02-00-00,05-24-11,20:00:00,REGULAR,3173590,1099055,901
24,A002,R051,02-00-00,05-25-11,00:00:00,REGULAR,3173803,1099079,213
25,A002,R051,02-00-00,05-25-11,04:00:00,REGULAR,3173826,1099081,23
26,A002,R051,02-00-00,05-25-11,08:00:00,REGULAR,3173873,1099178,47
27,A002,R051,02-00-00,05-25-11,12:00:00,REGULAR,3174022,1099496,149
28,A002,R051,02-00-00,05-25-11,16:00:00,REGULAR,3174309,1099572,287
29,A002,R051,02-00-00,05-25-11,20:00:00,REGULAR,3175172,1099651,863
...,...,...,...,...,...,...,...,...,...
7313,A042,R086,01-00-04,05-23-11,04:00:00,REGULAR,912616,4167855,10
7314,A042,R086,01-00-04,05-23-11,08:00:00,REGULAR,912622,4168025,6
7315,A042,R086,01-00-04,05-23-11,12:00:00,REGULAR,912679,4168923,57
7316,A042,R086,01-00-04,05-23-11,16:00:00,REGULAR,912843,4169719,164
7317,A042,R086,01-00-04,05-23-11,20:00:00,REGULAR,913194,4170521,351
7318,A042,R086,01-00-04,05-24-11,00:00:00,REGULAR,913291,4170682,97
7319,A042,R086,01-00-04,05-24-11,04:00:00,REGULAR,913300,4170711,9
7320,A042,R086,01-00-04,05-24-11,08:00:00,REGULAR,913309,4170890,9
7321,A042,R086,01-00-04,05-24-11,12:00:00,REGULAR,913360,4171856,51
7322,A042,R086,01-00-04,05-24-11,16:00:00,REGULAR,913536,4172582,176
7323,A042,R086,01-00-04,05-24-11,20:00:00,REGULAR,913892,4173464,356
7324,A042,R086,01-00-04,05-25-11,00:00:00,REGULAR,914006,4173624,114
7325,A042,R086,01-00-04,05-25-11,04:00:00,RECOVR,914020,4173655,14
7326,A042,R086,01-00-04,05-25-11,04:00:00,AUD,914020,4173655,0
7327,A042,R086,01-00-04,05-25-11,08:00:00,REGULAR,914027,4173813,7
7328,A042,R086,01-00-04,05-25-11,12:00:00,REGULAR,914087,4174759,60
7329,A042,R086,01-00-04,05-25-11,16:00:00,REGULAR,914262,4175544,175
7330,A042,R086,01-00-04,05-25-11,20:00:00,REGULAR,914686,4176445,424
7331,A042,R086,01-00-04,05-26-11,00:00:00,REGULAR,914808,4176633,122
7332,A042,R086,01-00-04,05-26-11,04:00:00,REGULAR,914822,4176664,14
7333,A042,R086,01-00-04,05-26-11,08:00:00,REGULAR,914830,4176849,8
7334,A042,R086,01-00-04,05-26-11,12:00:00,REGULAR,914902,4177778,72
7335,A042,R086,01-00-04,05-26-11,16:00:00,REGULAR,915105,4178603,203
7336,A042,R086,01-00-04,05-26-11,20:00:00,REGULAR,915583,4179421,478
7337,A042,R086,01-00-04,05-27-11,00:00:00,REGULAR,915724,4179647,141
7338,A042,R086,01-00-04,05-27-11,04:00:00,REGULAR,915737,4179675,13
7339,A042,R086,01-00-04,05-27-11,08:00:00,REGULAR,915743,4179820,6
7340,A042,R086,01-00-04,05-27-11,12:00:00,REGULAR,915806,4180746,63
7341,A042,R086,01-00-04,05-27-11,16:00:00,REGULAR,916090,4181746,284
7342,A042,R086,01-00-04,05-27-11,20:00:00,REGULAR,916517,4182631,427

In [41]:
# EASIER SOLUTION: USING THE METHOD SHIFT

upd=pd.read_csv('updated_turnstile-110528.txt', header=None) 
upd.columns=["C/A", "UNIT", "SCP", "DATEn", "TIMEn", "DESCn", "ENTRIESn", "EXITSn"]


upd['ENTRIESn_hourly']=upd.ENTRIESn-upd.ENTRIESn.shift(1).fillna(1)

In [42]:
upd

,C/A,UNIT,SCP,DATEn,TIMEn,DESCn,ENTRIESn,EXITSn,ENTRIESn_hourly
0,A002,R051,02-00-00,05-21-11,00:00:00,REGULAR,3169391,1097585,3169390.0
1,A002,R051,02-00-00,05-21-11,04:00:00,REGULAR,3169415,1097588,24.0
2,A002,R051,02-00-00,05-21-11,08:00:00,REGULAR,3169431,1097607,16.0
3,A002,R051,02-00-00,05-21-11,12:00:00,REGULAR,3169506,1097686,75.0
4,A002,R051,02-00-00,05-21-11,16:00:00,REGULAR,3169693,1097734,187.0
5,A002,R051,02-00-00,05-21-11,20:00:00,REGULAR,3169998,1097769,305.0
6,A002,R051,02-00-00,05-22-11,00:00:00,REGULAR,3170119,1097792,121.0
7,A002,R051,02-00-00,05-22-11,04:00:00,REGULAR,3170146,1097801,27.0
8,A002,R051,02-00-00,05-22-11,08:00:00,REGULAR,3170164,1097820,18.0
9,A002,R051,02-00-00,05-22-11,12:00:00,REGULAR,3170240,1097867,76.0
10,A002,R051,02-00-00,05-22-11,16:00:00,REGULAR,3170388,1097912,148.0
11,A002,R051,02-00-00,05-22-11,20:00:00,REGULAR,3170611,1097941,223.0
12,A002,R051,02-00-00,05-23-11,00:00:00,REGULAR,3170695,1097964,84.0
13,A002,R051,02-00-00,05-23-11,04:00:00,REGULAR,3170701,1097964,6.0
14,A002,R051,02-00-00,05-23-11,08:00:00,REGULAR,3170746,1098069,45.0
15,A002,R051,02-00-00,05-23-11,12:00:00,REGULAR,3170897,1098378,151.0
16,A002,R051,02-00-00,05-23-11,16:00:00,REGULAR,3171194,1098447,297.0
17,A002,R051,02-00-00,05-23-11,20:00:00,REGULAR,3172059,1098511,865.0
18,A002,R051,02-00-00,05-24-11,00:00:00,REGULAR,3172200,1098528,141.0
19,A002,R051,02-00-00,05-24-11,04:00:00,REGULAR,3172214,1098529,14.0
20,A002,R051,02-00-00,05-24-11,08:00:00,REGULAR,3172266,1098628,52.0
21,A002,R051,02-00-00,05-24-11,12:00:00,REGULAR,3172407,1098952,141.0
22,A002,R051,02-00-00,05-24-11,16:00:00,REGULAR,3172689,1099010,282.0
23,A002,R051,02-00-00,05-24-11,20:00:00,REGULAR,3173590,1099055,901.0
24,A002,R051,02-00-00,05-25-11,00:00:00,REGULAR,3173803,1099079,213.0
25,A002,R051,02-00-00,05-25-11,04:00:00,REGULAR,3173826,1099081,23.0
26,A002,R051,02-00-00,05-25-11,08:00:00,REGULAR,3173873,1099178,47.0
27,A002,R051,02-00-00,05-25-11,12:00:00,REGULAR,3174022,1099496,149.0
28,A002,R051,02-00-00,05-25-11,16:00:00,REGULAR,3174309,1099572,287.0
29,A002,R051,02-00-00,05-25-11,20:00:00,REGULAR,3175172,1099651,863.0
...,...,...,...,...,...,...,...,...,...
7313,A042,R086,01-00-04,05-23-11,04:00:00,REGULAR,912616,4167855,10.0
7314,A042,R086,01-00-04,05-23-11,08:00:00,REGULAR,912622,4168025,6.0
7315,A042,R086,01-00-04,05-23-11,12:00:00,REGULAR,912679,4168923,57.0
7316,A042,R086,01-00-04,05-23-11,16:00:00,REGULAR,912843,4169719,164.0
7317,A042,R086,01-00-04,05-23-11,20:00:00,REGULAR,913194,4170521,351.0
7318,A042,R086,01-00-04,05-24-11,00:00:00,REGULAR,913291,4170682,97.0
7319,A042,R086,01-00-04,05-24-11,04:00:00,REGULAR,913300,4170711,9.0
7320,A042,R086,01-00-04,05-24-11,08:00:00,REGULAR,913309,4170890,9.0
7321,A042,R086,01-00-04,05-24-11,12:00:00,REGULAR,913360,4171856,51.0
7322,A042,R086,01-00-04,05-24-11,16:00:00,REGULAR,913536,4172582,176.0
7323,A042,R086,01-00-04,05-24-11,20:00:00,REGULAR,913892,4173464,356.0
7324,A042,R086,01-00-04,05-25-11,00:00:00,REGULAR,914006,4173624,114.0
7325,A042,R086,01-00-04,05-25-11,04:00:00,RECOVR,914020,4173655,14.0
7326,A042,R086,01-00-04,05-25-11,04:00:00,AUD,914020,4173655,0.0
7327,A042,R086,01-00-04,05-25-11,08:00:00,REGULAR,914027,4173813,7.0
7328,A042,R086,01-00-04,05-25-11,12:00:00,REGULAR,914087,4174759,60.0
7329,A042,R086,01-00-04,05-25-11,16:00:00,REGULAR,914262,4175544,175.0
7330,A042,R086,01-00-04,05-25-11,20:00:00,REGULAR,914686,4176445,424.0
7331,A042,R086,01-00-04,05-26-11,00:00:00,REGULAR,914808,4176633,122.0
7332,A042,R086,01-00-04,05-26-11,04:00:00,REGULAR,914822,4176664,14.0
7333,A042,R086,01-00-04,05-26-11,08:00:00,REGULAR,914830,4176849,8.0
7334,A042,R086,01-00-04,05-26-11,12:00:00,REGULAR,914902,4177778,72.0
7335,A042,R086,01-00-04,05-26-11,16:00:00,REGULAR,915105,4178603,203.0
7336,A042,R086,01-00-04,05-26-11,20:00:00,REGULAR,915583,4179421,478.0
7337,A042,R086,01-00-04,05-27-11,00:00:00,REGULAR,915724,4179647,141.0
7338,A042,R086,01-00-04,05-27-11,04:00:00,REGULAR,915737,4179675,13.0
7339,A042,R086,01-00-04,05-27-11,08:00:00,REGULAR,915743,4179820,6.0
7340,A042,R086,01-00-04,05-27-11,12:00:00,REGULAR,915806,4180746,63.0
7341,A042,R086,01-00-04,05-27-11,16:00:00,REGULAR,916090,4181746,284.0
7342,A042,R086,01-00-04,05-27-11,20:00:00,REGULAR,916517,4182631,427.0

In [43]:
# EASIER SOLUTION: USING THE METHOD SHIFT

upd=pd.read_csv('updated_turnstile-110528.txt', header=None) 
upd.columns=["C/A", "UNIT", "SCP", "DATEn", "TIMEn", "DESCn", "ENTRIESn", "EXITSn"]


upd['EXITSn_hourly']=upd.EXITSn-upd.EXITSn.shift(1).fillna(1)

In [44]:
upd

,C/A,UNIT,SCP,DATEn,TIMEn,DESCn,ENTRIESn,EXITSn,EXITSn_hourly
0,A002,R051,02-00-00,05-21-11,00:00:00,REGULAR,3169391,1097585,1097584.0
1,A002,R051,02-00-00,05-21-11,04:00:00,REGULAR,3169415,1097588,3.0
2,A002,R051,02-00-00,05-21-11,08:00:00,REGULAR,3169431,1097607,19.0
3,A002,R051,02-00-00,05-21-11,12:00:00,REGULAR,3169506,1097686,79.0
4,A002,R051,02-00-00,05-21-11,16:00:00,REGULAR,3169693,1097734,48.0
5,A002,R051,02-00-00,05-21-11,20:00:00,REGULAR,3169998,1097769,35.0
6,A002,R051,02-00-00,05-22-11,00:00:00,REGULAR,3170119,1097792,23.0
7,A002,R051,02-00-00,05-22-11,04:00:00,REGULAR,3170146,1097801,9.0
8,A002,R051,02-00-00,05-22-11,08:00:00,REGULAR,3170164,1097820,19.0
9,A002,R051,02-00-00,05-22-11,12:00:00,REGULAR,3170240,1097867,47.0
10,A002,R051,02-00-00,05-22-11,16:00:00,REGULAR,3170388,1097912,45.0
11,A002,R051,02-00-00,05-22-11,20:00:00,REGULAR,3170611,1097941,29.0
12,A002,R051,02-00-00,05-23-11,00:00:00,REGULAR,3170695,1097964,23.0
13,A002,R051,02-00-00,05-23-11,04:00:00,REGULAR,3170701,1097964,0.0
14,A002,R051,02-00-00,05-23-11,08:00:00,REGULAR,3170746,1098069,105.0
15,A002,R051,02-00-00,05-23-11,12:00:00,REGULAR,3170897,1098378,309.0
16,A002,R051,02-00-00,05-23-11,16:00:00,REGULAR,3171194,1098447,69.0
17,A002,R051,02-00-00,05-23-11,20:00:00,REGULAR,3172059,1098511,64.0
18,A002,R051,02-00-00,05-24-11,00:00:00,REGULAR,3172200,1098528,17.0
19,A002,R051,02-00-00,05-24-11,04:00:00,REGULAR,3172214,1098529,1.0
20,A002,R051,02-00-00,05-24-11,08:00:00,REGULAR,3172266,1098628,99.0
21,A002,R051,02-00-00,05-24-11,12:00:00,REGULAR,3172407,1098952,324.0
22,A002,R051,02-00-00,05-24-11,16:00:00,REGULAR,3172689,1099010,58.0
23,A002,R051,02-00-00,05-24-11,20:00:00,REGULAR,3173590,1099055,45.0
24,A002,R051,02-00-00,05-25-11,00:00:00,REGULAR,3173803,1099079,24.0
25,A002,R051,02-00-00,05-25-11,04:00:00,REGULAR,3173826,1099081,2.0
26,A002,R051,02-00-00,05-25-11,08:00:00,REGULAR,3173873,1099178,97.0
27,A002,R051,02-00-00,05-25-11,12:00:00,REGULAR,3174022,1099496,318.0
28,A002,R051,02-00-00,05-25-11,16:00:00,REGULAR,3174309,1099572,76.0
29,A002,R051,02-00-00,05-25-11,20:00:00,REGULAR,3175172,1099651,79.0
...,...,...,...,...,...,...,...,...,...
7313,A042,R086,01-00-04,05-23-11,04:00:00,REGULAR,912616,4167855,27.0
7314,A042,R086,01-00-04,05-23-11,08:00:00,REGULAR,912622,4168025,170.0
7315,A042,R086,01-00-04,05-23-11,12:00:00,REGULAR,912679,4168923,898.0
7316,A042,R086,01-00-04,05-23-11,16:00:00,REGULAR,912843,4169719,796.0
7317,A042,R086,01-00-04,05-23-11,20:00:00,REGULAR,913194,4170521,802.0
7318,A042,R086,01-00-04,05-24-11,00:00:00,REGULAR,913291,4170682,161.0
7319,A042,R086,01-00-04,05-24-11,04:00:00,REGULAR,913300,4170711,29.0
7320,A042,R086,01-00-04,05-24-11,08:00:00,REGULAR,913309,4170890,179.0
7321,A042,R086,01-00-04,05-24-11,12:00:00,REGULAR,913360,4171856,966.0
7322,A042,R086,01-00-04,05-24-11,16:00:00,REGULAR,913536,4172582,726.0
7323,A042,R086,01-00-04,05-24-11,20:00:00,REGULAR,913892,4173464,882.0
7324,A042,R086,01-00-04,05-25-11,00:00:00,REGULAR,914006,4173624,160.0
7325,A042,R086,01-00-04,05-25-11,04:00:00,RECOVR,914020,4173655,31.0
7326,A042,R086,01-00-04,05-25-11,04:00:00,AUD,914020,4173655,0.0
7327,A042,R086,01-00-04,05-25-11,08:00:00,REGULAR,914027,4173813,158.0
7328,A042,R086,01-00-04,05-25-11,12:00:00,REGULAR,914087,4174759,946.0
7329,A042,R086,01-00-04,05-25-11,16:00:00,REGULAR,914262,4175544,785.0
7330,A042,R086,01-00-04,05-25-11,20:00:00,REGULAR,914686,4176445,901.0
7331,A042,R086,01-00-04,05-26-11,00:00:00,REGULAR,914808,4176633,188.0
7332,A042,R086,01-00-04,05-26-11,04:00:00,REGULAR,914822,4176664,31.0
7333,A042,R086,01-00-04,05-26-11,08:00:00,REGULAR,914830,4176849,185.0
7334,A042,R086,01-00-04,05-26-11,12:00:00,REGULAR,914902,4177778,929.0
7335,A042,R086,01-00-04,05-26-11,16:00:00,REGULAR,915105,4178603,825.0
7336,A042,R086,01-00-04,05-26-11,20:00:00,REGULAR,915583,4179421,818.0
7337,A042,R086,01-00-04,05-27-11,00:00:00,REGULAR,915724,4179647,226.0
7338,A042,R086,01-00-04,05-27-11,04:00:00,REGULAR,915737,4179675,28.0
7339,A042,R086,01-00-04,05-27-11,08:00:00,REGULAR,915743,4179820,145.0
7340,A042,R086,01-00-04,05-27-11,12:00:00,REGULAR,915806,4180746,926.0
7341,A042,R086,01-00-04,05-27-11,16:00:00,REGULAR,916090,4181746,1000.0
7342,A042,R086,01-00-04,05-27-11,20:00:00,REGULAR,916517,4182631,885.0